### ISSUE TITLE
Generic error

### ISSUE THREAD

**Issue by stegarcia** [ec-jrc/re3gistry#1]
I installed re3gistry following the installation guide and I have a generic error but I don't know where to look for more information on this bug

Here is the address of my server:
https://dgiwg.ign.fr/re3gistry/

**Comment by df-git** [comment]
I think this issue is related to the old version of the Re3gistry 1.3.x.
For that version, you can refer to this space: https://joinup.ec.europa.eu/solution/re3gistry
