### ISSUE TITLE
Question on status localization

### ISSUE THREAD

**Issue by heidivanparys** [ec-jrc/re3gistry#105]
Table `REG_STATUSLOCALIZATION` contains the content as displayed in our instance. Those rows were inserted when setting up the database schema, and they were updated during the installation process, according to the `EDITDATE` and according to https://github.com/ec-jrc/re3gistry/blob/79f806053066cfa1fb1636ce34b64912004ccb32/sources/Re3gistry2JavaAPI/src/main/java/eu/europa/ec/re3gistry2/javaapi/handler/RegInstallationStepCleanInstallationProcessHandler.java#L149-L159.

The master language is Danish, and both Danish and English are set up to be active languages in the system.

Questions:

- How can the translation to Danish for the different statuses be done? Is there a GUI for this, or should it be done directly in the database?
- How to add the English translation for the statuses to the system? Is this possible? If yes, is there a GUI for this, or should it be done directly in the database?

|UUID|REG_STATUS|REG_STATUSGROUP|LABEL|DESCRIPTION|REG_LANGUAGECODE|INSERTDATE|EDITDATE|
|----|----------|---------------|-----|-----------|----------------|----------|--------|
|status-ml||1|Status||da|2017-05-11 14:14:05.338|2021-11-11 09:56:21.800|
|valid-ml|1||Valid||da|2017-05-11 14:14:05.338|2021-11-11 09:56:21.808|
|invalid-ml|2||invalid||da|2017-05-11 14:14:05.338|2021-11-11 09:56:21.782|
|superseded-ml|3||Superseded||da|2017-05-11 14:14:05.338|2021-11-11 09:56:21.805|
|retired-ml|4||Retired||da|2017-05-11 14:14:05.338|2021-11-11 09:56:21.797|
|draft-ml|5||Draft||da|2017-05-11 14:14:05.338|2021-11-11 09:56:21.780|
|submitted-ml|6||Submitted||da|2017-05-11 14:14:05.338|2021-11-11 09:56:21.803|
|needreview-ml|7||Need review||da|2017-05-11 14:14:05.338|2021-11-11 09:56:21.786|
|proposed-ml|8||proposed||da|2017-05-11 14:14:05.338|2021-11-11 09:56:21.791|
|notaccepted-ml|9||Not accepted||da|2017-05-11 14:14:05.338|2021-11-11 09:56:21.788|
|acceptedWithChanges-ml|10||Accepted With Changes||da|2017-05-11 14:14:05.338|2021-11-11 09:56:21.774|
|changesCompleted-ml|11||Changes Completed||da|2017-05-11 14:14:05.338|2021-11-11 09:56:21.777|
|accepted-ml|12||Accepted||da|2017-05-11 14:14:05.338|2021-11-11 09:56:21.771|
|withdrawn-ml|13||Withdrawn||da|2017-05-11 14:14:05.338|2021-11-11 09:56:21.811|
|published-ml|14||Published||da|2017-05-11 14:14:05.338|2021-11-11 09:56:21.793|

|UUID|LABEL|ISO6391CODE|ISO6392CODE|MASTERLANGUAGE|ACTIVE|INSERTDATE|EDITDATE|
|----|-----|-----------|-----------|--------------|------|----------|--------|
|en|english|en|eng|0|1|2017-05-11 14:14:05.338|2021-11-11 09:56:21.414|
|it|italiano|it|ita|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.362|
|cs|czech|cs|cze|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.338|
|bg|bulgarian|bg|bul|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.335|
|da|danish|da|dan|1|1|2017-05-11 14:14:05.338|2021-11-11 09:56:21.422|
|de|german|de|ger|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.341|
|el|greek|el|gre|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.344|
|es|spanish|es|spa|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.346|
|et|estonian|et|est|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.349|
|fi|finnish|fi|fin|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.352|
|fr|french|fr|fra|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.354|
|hu|hungarian|hu|hun|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.359|
|lt|lithuanian|lt|lit|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.365|
|lv|latvian|lv|lav|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.368|
|mt|maltese|mt|mlt|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.371|
|pl|polish|pl|pol|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.377|
|nl|dutch|nl|dut|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.374|
|pt|portuguese|pt|por|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.380|
|ro|romanian|ro|rum|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.382|
|sk|slovak|sk|slo|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.385|
|sl|slovenian|sl|slv|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.388|
|sv|swedish|sv|swe|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.392|
|hr|croatian|hr|hrv|0|0|2017-05-11 14:14:05.338|2021-11-11 09:56:21.357|

**Comment by emanuelaepure10** [comment]
Hi,

The only way we are doing it at the moment is by the initialization script that we are running before to start the system.

It could probably be added to the management interface as well but at the time beeing is not in our future plans.

Best regards
