### ISSUE TITLE
Question on CacheAll and languages

### ISSUE THREAD

**Issue by heidivanparys** [ec-jrc/re3gistry#108]
In the following code:

https://github.com/ec-jrc/re3gistry/blob/79f806053066cfa1fb1636ce34b64912004ccb32/sources/Re3gistry2RestAPI/src/main/java/eu/europa/ec/re3gistry2/restapi/CacheAllServlet.java#L69-L86

why is `languageManager.getAll()` used and not `languageManager.getAllActive()`?

This process seems to take quite some time (20 minutes for our test installation with a limited amount of data), so only caching the active languages (in our installation, we only have two active languages) could help to speed it up? Avoid unnecessary queries to the database?

**Comment by emanuelaepure10** [comment]
Indead, that;s a perfect question.
I completely agree that languageManager.getAllActive() is the method to be called.

Thank you for reporting it.

**Comment by emanuelaepure10** [comment]
https://github.com/ec-jrc/re3gistry/commit/90fa0c1fb1468d6d9ee28d5530a5fbc02408cc7e
