### ISSUE TITLE
Detailed guide

### ISSUE THREAD

**Issue by MartinTuchyna** [ec-jrc/re3gistry#11]
Is there available more detailed user / admin manual for the Re3Gistry?
[Re3gistry 2 – Quick start guide](https://github.com/ec-jrc/re3gistry/blob/master/Quick-start-guide.md) is good start, but in order to test the system, user needs more detailed information, e.g.
How to setup the Registry?
How to setup the Registers under the registry?
How to create the content for the particular register?
What are the roles in the system and how to manage them?
What are the defined processes behind, how are they related to the parts of the system and what is related functionality (what is behaviour - eg. what shall expect admin, and what user) for the particular parts of the system?
etc.
Without that basic information, is quite challenge to understand, what is ok, and where might be the issue. See another issues.

Thanks, Martin

**Comment by df-git** [comment]
Dear Martin,
The detailed guide has now been published.
Best regards
