### ISSUE TITLE
Not possible to create field with field type “parent” via GUI

### ISSUE THREAD

**Issue by heidivanparys** [ec-jrc/re3gistry#119]
I followed the step-by-step guidance at https://github.com/ec-jrc/re3gistry/issues/42#issuecomment-829172097 to create a register that can contain hierarchical code lists.

However, what is described for step 2.6 / 3.2 does not work for me.

- The field with name “parent” and type “parent” is not present (I don't know whether it is supposed to be a field that should be present from the start, as the field “definition” e.g.)
- It is not possible to create a new field with type “parent”, see screenshot.

![image](https://user-images.githubusercontent.com/11427611/145823027-4ac20aa4-8fab-4829-bc20-defdd054c18f.png)

A workaround was to create a new field with type e.g. “text”, and then change its field type to “parent” (uuid = '7') directly in the database:

![image](https://user-images.githubusercontent.com/11427611/145829163-63a2a3ad-844b-4adb-90a1-b3d5c007e090.png)

That new field could then be used in the item class:

![image](https://user-images.githubusercontent.com/11427611/145829331-0a54e3a9-5e39-43a6-834c-df951a458187.png)

![image](https://user-images.githubusercontent.com/11427611/145829472-4c80800e-881c-4b96-8fad-9f629e471399.png)

**Comment by emanuelaepure10** [comment]
@oscar9 
The same problem happens as well with the successor and predecessor. When an item is superseded the successor/predecessor doesn't appear.
Probably the best is to add the 3 fields in the init script of the database, 
or to create on the fly successor/predecessor fields when there is a supersession, but this wouldn't solve the parent problem.
