### ISSUE TITLE
Visibility of the new SK Registry

### ISSUE THREAD

**Issue by MartinTuchyna** [ec-jrc/re3gistry#12]
I have created the new registry called "SK Registry" (URI https://inspire-sandbox.jrc.ec.europa.eu/registry/SK). Why after I published this registry I can not see anything in the Publication interface? (https://inspire-sandbox.jrc.ec.europa.eu/registry)

**Comment by df-git** [comment]
Dear Martin,
You can see your register here: https://inspire-sandbox.jrc.ec.europa.eu/registry/SK.
The propagation of the publication takes some minutes, since the Solr indexes need to be updated.
Furthermore, the "Namespace Register" is not visible, since it is still "proposed".

**Comment by MartinTuchyna** [comment]
Thanks, now I see it. It would be good to provide some info about this delay, justo to eliminate the same questions in the future from other users.
