### ISSUE TITLE
Documentation IT architecture

### ISSUE THREAD

**Issue by heidivanparys** [ec-jrc/re3gistry#123]
It would be good if the IT architecture of the system could be documented in the manual. I made the following attempt, using the [C4 model](https://c4model.com/) approach.

Any feedback on these diagrams would be very welcome, perhaps I understood certain parts in the wrong way.

![image](https://user-images.githubusercontent.com/11427611/146010829-7e0a7ff9-f0e6-42f8-bbdc-2df95576b59f.png)

![image](https://user-images.githubusercontent.com/11427611/146010927-b5f53ad8-6d8e-4789-a710-11a485cda9d1.png)

![image](https://user-images.githubusercontent.com/11427611/146012725-331e68e7-a585-4aa1-ba99-fda619210125.png)

![image](https://user-images.githubusercontent.com/11427611/146010975-b1fdd5f2-b99b-4013-a8a6-ccac5ec8a93d.png)

![image](https://user-images.githubusercontent.com/11427611/146010997-e8c7e7bd-1ad9-4d0f-8ad4-f4056e462c84.png)

**Comment by emanuelaepure10** [comment]
Dear @heidivanparys 

This is so great what you have done here.
Congratulations! 

And a big Thank you

**Comment by oscar9** [comment]
Dear @heidivanparys 

Many thanks for take your time to create these diagrams. We are going to include them in the documentation that we are updating. Do you still have the code that create these C4 models? In that case, could you share them with us? The diagrams in the roadmap are going to use the mermaid library to be drawn in GitHub. I’ve checked and found that they are also working in the [support for C4 models](https://github.com/mermaid-js/mermaid/issues/1276). It would be great if we have the C4 diagram code so we can transform them in mermaid code. In the future, if this support become available, it will be easy to update the diagrams in case of change.

Thanks in advance

Best regards

**Comment by heidivanparys** [comment]
I used a custom-developed MDG for Sparx Enterprise Architect to create those diagrams.

What you need to see those diagrams in [Enterprise Architect](https://www.sparxsystems.com/products/ea/index.html), provided that you have that tool:

- [C4 MDG.txt](https://github.com/ec-jrc/re3gistry/files/8702869/C4.MDG.txt): change extension to XML and [import as MDG technology in EA](https://sparxsystems.com/enterprise_architect_user_guide/15.2/modeling/importmdgtechnologies.html)
- make sure that both the C4 Model and Custom Diagram Style MDGs [are enabled](https://sparxsystems.com/enterprise_architect_user_guide/15.2/modeling/manage_mdg_technologies.html), see also screenshot below
- [image assets.txt](https://github.com/ec-jrc/re3gistry/files/8702964/image.assets.txt): change extension to XMI and [import the package](https://sparxsystems.com/enterprise_architect_user_guide/15.2/model_publishing/importxmi.html) (contains some icons)
- [it architecture re3gistry XMI.txt](https://github.com/ec-jrc/re3gistry/files/8702954/it.architecture.re3gistry.XMI.txt): change extension to XMI and [import the package](https://sparxsystems.com/enterprise_architect_user_guide/15.2/model_publishing/importxmi.html) (contains the actual model)

![image](https://user-images.githubusercontent.com/11427611/168667252-5d4bc255-f521-448d-8154-0a3d3ced3e5b.png)

I exported the descriptions of the different model elements to a CSV file, in case the EA model cannot be used, see [re3gistry_descriptions.csv](https://github.com/ec-jrc/re3gistry/files/8702891/re3gistry_descriptions.csv) (but you'll still have to add the relations in your tool of choice).

**Comment by oscar9** [comment]
All the diagrams have been included in the developer documentation, soon they will be part of the master branch. Thanks for your collaboration.
