### ISSUE TITLE
Malformed XML for XML export when label contains whitespace

### ISSUE THREAD

**Issue by heidivanparys** [ec-jrc/re3gistry#124]
Export to XML (`format=xml`) gives malformed XML when the label contains whitespace, see screenshots.

I don't have a solution, but one option could perhaps be to use the local id of the field in the export, instead of the label of that field in the requested language.

![image](https://user-images.githubusercontent.com/11427611/146025369-5eb5d66b-4eec-4bbb-a33b-df371fc173cb.png)

![image](https://user-images.githubusercontent.com/11427611/146025721-4950d2b7-490a-42b7-bdc0-a662823e86cb.png)

![image](https://user-images.githubusercontent.com/11427611/146025820-2f1f267f-c7fb-4432-8e2c-a2ce6522d23f.png)

**Comment by emanuelaepure10** [comment]
This 
https://github.com/ec-jrc/re3gistry/commit/e6820bfd0d8c148ea656a057cd0e0aea811d05a6
should solve the problem both for XML and JSON
