### ISSUE TITLE
Allow importing registers and code lists from native RDF files

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#139]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Many code lists are using this format and that would allow the user to do less cleaning to insert them into the system

# Proposed change
Allow importing registers and code lists from native RDF files

# Alternatives

# Funding

# Additional information

**Comment by jescriu** [comment]
After having analysed this enhancement the JRC INSPIRE team has decided to postpone its potential implementation waiting for the upcoming discussion on the future of the Re3gistry open-source software.
For the above-mentioned reason, this item is temporarily closed.
