### ISSUE TITLE
What is the meaning and the possibilities of the roles

### ISSUE THREAD

**Issue by MartinTuchyna** [ec-jrc/re3gistry#14]
When creating the new Register (https://inspire-sandbox.jrc.ec.europa.eu/re3gistry2/addRegister?itemUuid=27f3dbdc7dbc69e5c2b3aa3ef79dc491)
there are elements like:
- registerOwner
- registerManager
- controlBody
- submittingOrganization

What these roles means?
Where they are defined?
How shall be these uses?

Thanks, Martin

**Comment by df-git** [comment]
Dear Martin,
This is a topic that will be more clear once the user guide will be available.
The roles are needed to manage the "approval workflow" and to allow the user (with a specific role) to access only the action related to that user.
In particular, the roles available in the Re3gistry 2, are coming from the ISO 19135 standard.
Your user in the context of the current test-bed, has the higher privileges (Registry Manager).

**Comment by MartinTuchyna** [comment]
Thank you. 
Indeed, roles of the system and their description (what can be done) will also help better evaluate the potencial of deployment.
