### ISSUE TITLE
Adapt the API and its documentation to the Open API specifications

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#140]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Actual API documentation (api.html)

# Proposed change
Adapt the API and its documentation to the Open API specifications

# Alternatives
Use Open API specifications to make the documentation ....

# Funding

# Additional information

**Comment by unaibrrgn** [comment]
Swagger and the OpenAPI documentation has been added. All endpoints are visible in the Swagger API UI.
