### ISSUE TITLE
Improving the “search” functionality [adding and adjusting further options]

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#141]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation

# Proposed change
1. Add new search option that allows you to select a code list or collection of item,
once  a register has been selected from the drop-down menu from the search page results.

2. Add a filter to sort by edit date

3. Would be nice as well to be able to select the language to be used for search.

# Alternatives

# Funding

# Additional information

**Comment by arantzaetxebarria** [comment]
Close this issue as it is included in https://github.com/ec-jrc/re3gistry/issues/181
