### ISSUE TITLE
Adding a code

### ISSUE THREAD

**Issue by marcingrudzien** [ec-jrc/re3gistry#143]
Hi,

I am new to the Re3gisty software. I just have installed the software in version 2.3.1 using recommended components and their versions on Debian 11 following the administrator manual. The software started. Therefore, I wanted to publish one code list for testing which basically extends https://inspire.ec.europa.eu/codelist/LandCoverClassValue with the Polish national specific code list.

Therefore, I created a simple structure. 
![image](https://user-images.githubusercontent.com/25637709/167606130-926db6c8-7a3e-43a1-8d02-3c6a28cb4d47.png)

And I have stuck. I am not able to add any reference code to the code list. According to the user manual, there should be such action https://github.com/ec-jrc/re3gistry/blob/v2.3.0/documentation/user-manual.md#add-new-reference-codes in submitting organisation menu. However, in my case the menu is empty. 
![image](https://user-images.githubusercontent.com/25637709/167606780-be87b1d1-2647-4ee3-999f-fcbf9954e35c.png)

The same applies to Control Body and Register Manager menu. They are also empty.

The root user I use has all the necessary roles/associated groups.
![image](https://user-images.githubusercontent.com/25637709/167607676-e6918078-fa2f-4007-a0a9-8451d60b8897.png)

I might have missed something. I will appreciate any help.

Best regards,
Marcin

**Comment by emanuelaepure10** [comment]
Dear @marcingrudzien 

Could you please share with us if you have already created and publish the INSPIRE register?
If is public that you should be able to add items to it.

Thank you in advanced

**Comment by marcingrudzien** [comment]
Hi @emanuelaepure10 

I have published the entire registry
![image](https://user-images.githubusercontent.com/25637709/167619304-71fc4c60-62fe-407e-8bd9-45bcae41e470.png)
I am not sure whether it is the same as publishing INSPIRE register only. As I mentioned before Register Manager menu is empty.
![image](https://user-images.githubusercontent.com/25637709/167619744-74502c33-a49b-4494-b2e2-14ed52abc21e.png)

**Comment by emanuelaepure10** [comment]
Hi @marcingrudzien 

If not you go inside the register, somewhere bellow the description you should have the option to add by bulk many items together or just ad item by item, so a button called "Add item". Do you see them?

Thank you

**Comment by emanuelaepure10** [comment]
In the last image the interface just tells you that there is not action pending, as you have already publish everything.

**Comment by marcingrudzien** [comment]
Thank you @emanuelaepure10 
With your help I managed to find the functionality I was looking for.

You can close the issue
