### ISSUE TITLE
Option during installation for simplified management workflow

### ISSUE THREAD

**Issue by oscar9** [ec-jrc/re3gistry#144]
# Background and Motivation

The Re3gistry software, developed within the scope of the INSPIRE Directive, has been directly aligned to the workflow defined in ISO19135, where submitting organizations and a control body are taking part of its content management by using an appropriate set of registers. Using and understanding this workflow (ISO19135) may be difficult and complex for non-INSPIRE users, or first-time users of the software.

# Proposed change

Create and allow, as an optional feature, a configuration for using a simplified management workflow during the installation of the Re3gistry software. This simplified workflow might be only considering the submitting organisation and registry manager roles, or even simpler with just the registry manager role.

# Alternatives

# Funding

# Additional information

**Comment by heidivanparys** [comment]
The ISO 19135 standard is currently [under revision](https://www.iso.org/standard/83471.html), and that revision project is currently still in the preparatory stage (see also https://www.iso.org/stages-and-resources-for-standards-development.html for the stages). In short, that means that there still is a fair chance to have change requests discussed in the project team (the project leader, @ronaldtse, will hopefully correct me if I'm wrong!). Any input regarding ISO standards can be registered at the [ISO/TC 211 StandardsTracker](https://github.com/ISO-TC211/StandardsTracker).

@emanuelaepure10  If the JRC team has any input regarding the standard, then please also get in touch with TC 211.

**Comment by jescriu** [comment]
Dear @heidivanparys ,
Thank you for bringing us the topic on the revision of ISO19135. Obviously we have to be aligned with both, the current and the future version of the standard.
I will bring this topic to the next coordination meeting with OGC.
Thank you.

**Comment by ronaldtse** [comment]
Thank you @heidivanparys for connecting! Indeed the project team is open to feedback and we do meet regularly, so feel free to let us know anytime via the ISO/TC 211 StandardsTracker (as pointed out by @heidivanparys ).

**Comment by PeterParslow** [comment]
Oscar, Alexander Kotsev asked me to comment on this (he & I have a regular ISO/TC211 - JRC catch up).

Our ongoing revision needn't stop you developing software that implements a defined subset of the standard.

Ron Tse is the project lead, and as he says above, you can make your input via our 'standards tracker' (GitHub: as shared by Heidi above) - we'd love "INSPIRE's" input, as a key user of the current edition of the standard (as are the IHO)

If you'd prefer to wait & see what the revised edition has in store, then we are expecting a "committee draft" for comment quite soon, which you would be able to read (& comment on) as JRC is a liaison organisation. Alexander & Jordi should be notified when it's available.

**Comment by arantzaetxebarria** [comment]
This issue is closed as the simplified management workflow is implemented under [v2.4.0 release](https://github.com/ec-jrc/re3gistry/releases/tag/v2.4.0) 
To follow up on comments included in this ticket, the comments are moved to the [discussion section](https://github.com/ec-jrc/re3gistry/discussions/237).
