### ISSUE TITLE
Frontend installation

### ISSUE THREAD

**Issue by marcingrudzien** [ec-jrc/re3gistry#145]
Hi,

I am new to the Re3gisty software. I just have installed the software in version 2.3.1 using recommended components and their versions on Debian 11 following the administrator manual. I have managed to set up and configure the sample registry and register. Now I want to expose it using the frontend.

When I try to launch the default website I got the error 
![image](https://user-images.githubusercontent.com/25637709/167862796-8823fcb9-05ff-4b66-b2ba-0ae25a8d9e47.png)

Further analysis using the DevTools in the web browser shows that accessing the endpoint 
http://192.168.10.33/rest?uri=http://192.168.10.33&lang=pl&format=jsonc
by the browser returns 
![image](https://user-images.githubusercontent.com/25637709/167863666-9904e2f3-6f87-47a5-8646-cd3bfe716190.png)

Everything is installed on the server located and available only in our local network.

I appreciate any suggestions/help regarding frontend installation and setup.

Best regards,
Marcin

**Comment by MichalMed** [comment]
I'm having the same issue.

**Comment by emanuelaepure10** [comment]
Dear @marcingrudzien,

As I see you are calling
http://192.168.10.33/rest?uri=http://192.168.10.33&lang=pl&format=jsonc

instead you should probably call
http://192.168.10.33/registry/rest?uri=http://192.168.10.33/registry&lang=pl&format=jsonc

Just if you didnt configure Apache in a different way that the suggested one.
Please let us know if the above link works

Many thanks

**Comment by emanuelaepure10** [comment]
Dear @MichalMed 

Could you please paste the error you are encountering?
Before checking the interface, the most important is ensure yourself that the API words.

Thank you

**Comment by marcingrudzien** [comment]
Dear @emanuelaepure10,

http://192.168.10.33/registry/rest?uri=http://192.168.10.33/registry&lang=pl&format=jsonc returns 404

That is why I have changed the default apache config to 
```
	## Proxy to expose the Re2gistry 2 rest API
	ProxyPass /rest http://localhost:8080/re3gistry2restapi/items/any
	ProxyPassReverse /rest http://localhost:8080/re3gistry2restapi/items/any
```

My goal is to have the final external URL of the registry to be set up to http://registry.geoportal.gov.pl (not for example http://geoportal.gov.pl/registry). Therefore, having this in mind I made appropriate changes to the installation procedure, which may have caused misconfiguration issues.

Best regards,
Marcin

**Comment by emanuelaepure10** [comment]
Dear @marcingrudzien 

From the url:
http://192.168.10.33/registry/rest?uri=http://192.168.10.33/registry&lang=pl&format=jsonc
the uri=http://192.168.10.33/registry is used to get the item from the database

If I would be you I would make it work as default, as we have and than change how you wish,
but please keep in mind that the uri from the API's call is the one that should exist in the database, 
otherwise you will always get a 404.

Is this
http://192.168.10.33/rest?uri=http://192.168.10.33/registry&lang=pl&format=jsonc
working?

Best regards

**Comment by marcingrudzien** [comment]
Dear @emanuelaepure10,

http://192.168.10.33/rest?uri=http://192.168.10.33/registry&lang=pl&format=jsonc returns 500 The server had an internal error

Best regards

**Comment by emanuelaepure10** [comment]
Then you have set in the apache configuration the call to the api something like
ProxyPass /registry/rest http://192.168.10.33/re3gistry2restapi/items/any Keepalive=On
ProxyPassReverse  /registry/rest http://192.168.10.33/re3gistry2restapi/items/any Keepalive=On

So, if this
http://192.168.10.33/registry/rest?uri=http://192.168.10.33/registry&lang=pl&format=jsonc returns 404
please check in your database if the localId of the you registry is called 'registry' and if the baseuri of the reg_itemclass registry is http://192.168.10.33

**Comment by marcingrudzien** [comment]
Dear @emanuelaepure10 

I decided to make a clean installation of Re3gistry2 software. With a help of our network admin, I managed to run the frontend app using the domain name, but only within my organisational network. 

After the changes, the frontend client application sends the following request http://registry.geoportal.gov.pl/registry/rest?uri=http%3A%2F%2Fregistry.geoportal.gov.pl&lang=pl&format=jsonc
which returns 
```
{
  "code": 500,
  "description": "The server had an internal error",
  "description-code": "internal-server-error"
}
```

I am using no default configuration of apache config only with small adjustments

```
<VirtualHost *:80>
	
	<Directory "/var/www/html">
		AllowOverride All
		Options -Indexes -FollowSymLinks
		Require all granted
	</Directory>

    DocumentRoot "/var/www/html"
    ServerName registry.geoportal.gov.pl
    
    ## Alias for the /registry path
    Alias /registry "/var/www/html"
    
    ProxyPreserveHost Off

	## Proxy to expose the Re2gistry 2 management interface
	ProxyPass /re3gistry2 http://localhost:8080/re3gistry2
	ProxyPassReverse /re3gistry2 http://localhost:8080/re3gistry2

	## Proxy to expose the Re2gistry 2 rest API
	ProxyPass /registry/rest http://localhost:8080/re3gistry2restapi/items/any
	ProxyPassReverse /registry/rest http://localhost:8080/re3gistry2restapi/items/any

	## Proxypass to expose the Re3gistry 2 Solr instance (select)
	ProxyPass /registry/searchapi http://localhost:8983/solr/re3gistry2/select
	ProxyPassReverse /registry/searchapi http://localhost:8983/solr/re3gistry2/select


	### Rewrite rules ###
	RewriteEngine on
	
	## Handling direct request to a file
	RewriteCond %{REQUEST_URI} !^/registry/js
	RewriteRule ^/(.*)/(.*)\.([a-z]{2})\.(json|xml|atom|csv|rdf|iso19135xml|ror)$ %{REQUEST_SCHEME}://%{HTTP_HOST}/registry/rest?lang=$3&uri=http://%{HTTP_HOST}/$1&format=$4 [P,L]
	
	## Handling content negotiation: json
	RewriteCond %{REQUEST_URI} !^/registry/rest
	RewriteCond %{HTTP_ACCEPT}  ^application/json$
	RewriteCond %{HTTP:Accept-Language} ([a-z]{2}) [OR]
	RewriteCond %{HTTP:Accept-Language} ^()$
	RewriteRule ^/(.*) %{REQUEST_SCHEME}://%{HTTP_HOST}/registry/rest?lang=%1&uri=http://%{HTTP_HOST}/$1&format=json [P,L]

	## Handling content negotiation: iso19135xml
	RewriteCond %{REQUEST_URI} !^/registry/rest
	RewriteCond %{HTTP_ACCEPT}  ^application/x-iso19135+xml$
	RewriteCond %{HTTP:Accept-Language} ([a-z]{2}) [OR]
	RewriteCond %{HTTP:Accept-Language} ^()$
	RewriteRule ^/(.*) %{REQUEST_SCHEME}://%{HTTP_HOST}/registry/rest?lang=%1&uri=http://%{HTTP_HOST}/$1&format=iso19135xml [P,L]

	## Handling content negotiation: re3gistry xml
	RewriteCond %{REQUEST_URI} !^/registry/rest
	RewriteCond %{HTTP_ACCEPT}  ^application/xml$
	RewriteCond %{HTTP:Accept-Language} ([a-z]{2}) [OR]
	RewriteCond %{HTTP:Accept-Language} ^()$
	RewriteRule ^/(.*) %{REQUEST_SCHEME}://%{HTTP_HOST}/registry/rest?lang=%1&uri=http://%{HTTP_HOST}/$1&format=xml [P,L]
											
	## Handling content negotiation: atom
	RewriteCond %{REQUEST_URI} !^/registry/rest
	RewriteCond %{HTTP_ACCEPT}  ^application/atom+xml$
	RewriteCond %{HTTP:Accept-Language} ([a-z]{2}) [OR]
	RewriteCond %{HTTP:Accept-Language} ^()$
	RewriteRule ^/(.*) %{REQUEST_SCHEME}://%{HTTP_HOST}/registry/rest?lang=%1&uri=http://%{HTTP_HOST}/$1&format=atom [P,L]

	## Handling content negotiation: atom
	RewriteCond %{REQUEST_URI} !^/registry/rest
	RewriteCond %{HTTP_ACCEPT}  ^application/rdf+xml$
	RewriteCond %{HTTP:Accept-Language} ([a-z]{2}) [OR]
	RewriteCond %{HTTP:Accept-Language} ^()$
	RewriteRule ^/(.*) %{REQUEST_SCHEME}://%{HTTP_HOST}/registry/rest?lang=%1&uri=http://%{HTTP_HOST}/$1&format=rdf [P,L]

	## Handling content negotiation: atom
	RewriteCond %{REQUEST_URI} !^/registry/rest
	RewriteCond %{HTTP_ACCEPT}  ^text/csv$
	RewriteCond %{HTTP:Accept-Language} ([a-z]{2}) [OR]
	RewriteCond %{HTTP:Accept-Language} ^()$
	RewriteRule ^/(.*) %{REQUEST_SCHEME}://%{HTTP_HOST}/registry/rest?lang=%1&uri=http://%{HTTP_HOST}/$1&format=csv [P,L]
	
	## Generic request to the registry
	RewriteCond %{REQUEST_URI} !^/re3gistry2
	RewriteCond %{REQUEST_URI} !^/registry/searchapi
	RewriteCond %{REQUEST_URI} !^/registry/search
	RewriteCond %{REQUEST_URI} !^/registry/rest
	RewriteCond %{REQUEST_URI} !^/registry/index\.html
	RewriteCond %{REQUEST_URI} !^/registry/js
	RewriteCond %{REQUEST_URI} !^/registry/css
	RewriteCond %{REQUEST_URI} !^/registry/img
	RewriteCond %{REQUEST_URI} !^/registry/conf
	RewriteCond %{REQUEST_URI} !^/registry/libs
	RewriteCond %{REQUEST_URI} !index\.html$
	RewriteCond %{REQUEST_URI} !\.json$
	RewriteRule ^/(.*) /index.html [L]


	## Handling search requests
	RewriteCond %{REQUEST_URI} !^/registry/searchapi
	RewriteRule ^/registry/search(.*) /search.html$1 [L]
	
	
	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
```

I would be grateful if you could indicate the table names I should be looking for when making changes in the database.

Best regards

**Comment by emanuelaepure10** [comment]
Dear @marcingrudzien 

That's so great to hear :-) 
the app is right to give you a 500 because you now you are calling
http://registry.geoportal.gov.pl/registry/rest?uri=http%3A%2F%2Fregistry.geoportal.gov.pl&lang=pl&format=jsonc

The API il looking in the database for an item like this uri=http%3A%2F%2Fregistry.geoportal.gov.pl
which you dont have. in the reg_itemclass for the registry you probably have the baseuri: http://192.168.10.33
Try to change it with the http://registry.geoportal.gov.pl

Lets see if this works. I have a doubt about not using the localID of the registry...
I would say thay http://registry.geoportal.gov.pl/registry/rest?uri=http%3A%2F%2Fregistry.geoportal.gov.pl/registry&lang=pl&format=jsonc will work but not this
http://registry.geoportal.gov.pl/registry/rest?uri=http%3A%2F%2Fregistry.geoportal.gov.pl&lang=pl&format=jsonc

In that case probably you need to change a bit the code in order to have back the registry item when no localid in added to the uri that calls the API's

Please let me know

**Comment by marcingrudzien** [comment]
Dear @emanuelaepure10,

Before reinstalling I droped and then created new database, so the value in reg_itemclass seems to be correct. Please take a look at screenshot from pgadmin.
![image](https://user-images.githubusercontent.com/25637709/168276379-32aa795c-b6bb-435c-817a-6b3547342dae.png)

http://registry.geoportal.gov.pl/registry/rest?uri=http%3A%2F%2Fregistry.geoportal.gov.pl/registry&lang=pl&format=jsonc also returns 500.

Best regards,
Marcin

**Comment by marcingrudzien** [comment]
Dear @emanuelaepure10 ,

Thank you for your help.

After several tries, I managed to make the front application running. :-) To be honest I do not know what finally helped. I was playing with API cache config.

However, I have noticed two new issues.
1. When I start the application using http://registry.geoportal.gov.pl/registry it works fine, but when I start it with http://registry.geoportal.gov.pl/ it shows the error message. Can it be fixed?

2. The second thing is the lack of support for Polish special characters like ł, ż, ź, ą, etc. They display fine on the starting website see below 
![image](https://user-images.githubusercontent.com/25637709/168334311-f03669ee-1057-4274-922f-60ef138a9a9d.png)

but they display incorrectly as question mark "?" when I go deeper into the registry structure (example below)
![image](https://user-images.githubusercontent.com/25637709/168334894-3ca87a64-51d8-4491-9151-5b2cbfb91086.png)

Can it be fixed?

Best regards,
Marcin

**Comment by oscar9** [comment]
Dear @marcingrudzien,

I'm glad to see your instance working. I encourage you to open two new issues with these errors that you found so you could keep an eye on them and we will do the proper analysis for each one separately. We will proced to close this issue. Thanks also for your collaboration giving feedback and temporal solutions for the issues.

Best regards,
Óscar

**Comment by MichalMed** [comment]
I've added new issue on incorrect language support https://github.com/ec-jrc/re3gistry/issues/150

**Comment by oscar9** [comment]
The issue has been solved and a new issue has been created to treat with special encoding characters.
