### ISSUE TITLE
Front end update of changes @ backend

### ISSUE THREAD

**Issue by arantzaetxebarria** [ec-jrc/re3gistry#148]
From: [MartinTuchyna](https://github.com/MartinTuchyna)

[original issue](https://github.com/INSPIRE-MIF/helpdesk-registry/issues/31)

> Dear Re3gistry team,
> 
> I have update updated label for the original register with name "[test1](https://er.hany.sk/test1)"
> ![image](https://user-images.githubusercontent.com/64014694/168762835-423f0519-4267-4aad-924a-69e81edcbba7.png)
> 
> into the value "Codelists"
> ![image](https://user-images.githubusercontent.com/64014694/168762868-2ed05653-e202-4835-ab0f-d9c84e449447.png)
> 
> Also updatge was aproved changes on all levels, I still don't see change on the front end.
> 
> Any idea, what might be the problem?
> 
> Thanks in advance,
> 
> Martin
>

**Comment by arantzaetxebarria** [comment]
From: [emanuelaepure10](https://github.com/emanuelaepure10)

> Hi @MartinTuchyna
> 
> Do you have the latest version?
> With the latest version we have done a nice improvement that before was not there, that on publishing an action as well the cache is updated so the page that you want to see.
> 
> Please let us know
> Best regards

**Comment by arantzaetxebarria** [comment]
From: [emanuelaepure10](https://github.com/emanuelaepure10)

> Hi Martin,
> 
> Here is the link to the latest commit
> https://github.com/ec-jrc/re3gistry/commit/7e08a046505a93decfa6d181069bf214db6fbc2e
> Please let us know if you still have the problems
> 
> Thank you

**Comment by oscar9** [comment]
Dear,
If we don’t receive new information about the issue, we will proceed to close it. Please, feel free to open it again in case of need.
Best regards,
Óscar
