### ISSUE TITLE
Where and how create the content for the register

### ISSUE THREAD

**Issue by MartinTuchyna** [ec-jrc/re3gistry#15]
When created the register called Namespace Register (https://inspire-sandbox.jrc.ec.europa.eu/re3gistry2/browse?itemUuid=681f2922a15b5dbf5c10efc99a1fdd4e&languageUuid=en)
where and how I can define the content of this register?

**Comment by df-git** [comment]
Dear Martin,
You can create the content (sub-items) of the item you proposed, once it has been approved following the approval workflow (you can refer also to #13 ).

**Comment by MartinTuchyna** [comment]
Thank you, but how can I for example change the order of the fields [in this table](https://inspire-sandbox.jrc.ec.europa.eu/re3gistry2/field?itemclassUuid=5dc2eea40a33f87298428e33c26e23b1&languageUuid=en&fieldUuid=dee6f74080921f0950eb10a06deb0831) (see also snap) for example to have name space field as the first one before the label?
![obrázok](https://user-images.githubusercontent.com/6195936/78616245-042fc380-7874-11ea-8cc7-5842ad8c84d6.png)

**Comment by df-git** [comment]
You can use the drag and drop feature on the first column (Display order).

**Comment by MartinTuchyna** [comment]
Thanks, this was cool. Anyway, this shall also be mentioned in guidance as important functionality.
