### ISSUE TITLE
Special characters are not viewed correctly

### ISSUE THREAD

**Issue by MichalMed** [ec-jrc/re3gistry#150]
Most of the European languages have some special characters, that are displayed incorrectly in the front-end application. It looks like it is saved in incorrect coding to the database (table reg_localization) and update of the data in the relation fixes the problem.

**Comment by oscar9** [comment]
Related #97

**Comment by oscar9** [comment]
Hi @MichalMed ,
I just fixed the code. From now on, it should treat well encoding from all parts of the program, not just in labels, but in descriptions, emails, etc. Please let us know if this fix works well for you, we are going to do some extra test.
