### ISSUE TITLE
Problem with Cache

### ISSUE THREAD

**Issue by geoase** [ec-jrc/re3gistry#152]
Cache files are generated on disk when I click on "Cache All" Button:
732K	./file/items-by-url_8e976504e2b7fa6bd21f6b9b87411de8fdb0989f/offheap-disk-store
8.0K	./file/items-by-url_8e976504e2b7fa6bd21f6b9b87411de8fdb0989f/value-serializer
744K	./file/items-by-url_8e976504e2b7fa6bd21f6b9b87411de8fdb0989f
728K	./file/items-by-uuid_7b54fbb14c56454535856932f90300167d70efb5/offheap-disk-store
8.0K	./file/items-by-uuid_7b54fbb14c56454535856932f90300167d70efb5/value-serializer
740K	./file/items-by-uuid_7b54fbb14c56454535856932f90300167d70efb5
1.5M	./file

But when I open a registry object in the webapp I get the following registry2restapi log:
http-nio-8080-exec-5] INFO org.ehcache.impl.internal.store.disk.OffHeapDiskStore - The index for data file ehcache-disk-store.data is more recent than the data file itself by 104ms : this is harmless.
[http-nio-8080-exec-5] INFO org.ehcache.core.EhcacheManager - Cache 'items-by-url' created in EhcacheManager.
[http-nio-8080-exec-5] INFO org.ehcache.core.EhcacheManager - Cache 'items-by-url' removed from EhcacheManager.

It takes some time for big Codelists to load. Do you think it is recaching again? If yes, why, I did not change anything.

Best
Georg

**Comment by oscar9** [comment]
Dear @geoase ,

Thanks for reporting the issue, an analysis is being done. We will keep you informed with our discoveries, and we will try to provide an answer as soon as possible. 
Meanwhile, can you give us more information about how big this registry it is? How many items approximately do you have?

Best regards,
Óscar

**Comment by oscar9** [comment]
Dear @geoase,

We have been reviewing this issue. We have the idea that if you go to your tomcat folder and delete manually all your cache, this action would force the application to regenerate the cache again. It looks like an issue with this cache generation.

To do this, access your tomcat folder, there should exist a folder called /work/ehcache/ folder that you should delete.

Let us know if this is working for you.

Best regards,
Óscar
