### ISSUE TITLE
Bulk import improvement - import an entire hierarchy

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#154]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Would be nice to be able to Bulk import in the same file more items of the same reg_itemclass but of more collections. 

# Proposed change
Example:
reg_itemclass A
reg_itemclass B with parent reg_itemclass A

Create the file for the bulk import to be imported at the level of reg_itemclass A but containing
items of reg_itemclass B but referring to at least one item in the reg_itemclass B.

Thank you
Emanuela

**Comment by juanpelegrina** [comment]
relate with issue #190

**Comment by jescriu** [comment]
After having analysed this enhancement the JRC INSPIRE team has decided to postpone its potential implementation waiting for the upcoming discussion on the future of the Re3gistry open-source software.
For the above-mentioned reason, this item is temporarily closed.
