### ISSUE TITLE
Updates from backend on frontend

### ISSUE THREAD

**Issue by arantzaetxebarria** [ec-jrc/re3gistry#155]
From: [MartinTuchyna](https://github.com/MartinTuchyna)

[original issue](https://github.com/INSPIRE-MIF/helpdesk-registry/issues/35)

> Dear Re3gistry team.
> 
> Is there some specific action needed in order to see changes executed on backend also on the frontend?
> 
> For example I have updated the title of the register "INSPIRE Roz??renia" on this instance: https://er.hany.sk/registry
> 
> in backend on "INSPIRE Rozsirenia": see snap,
> 
> obrázok
> 
> but change is not visible on the frontend even in incognito mode after cleared cache..
> 
> obrázok
> 
> Thanks,
> 
> Martin

**Comment by iratigarzon** [comment]
Dear @MartinTuchyna ,

Since this issue is from an older version of the app, we recommend installing the latest version. If you continue to experience this issue, please open a new ticket.

Best regards,

Irati
