### ISSUE TITLE
Providing alternative visualisations to the current "table view"

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#157]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Would be nice to have in the v.2.x.x the same type of view as actual production of the registry https://inspire.ec.europa.eu/metadata-codelist/PriorityDataset -> click "Switch to hierarchy view"

# Proposed change
Providing alternative visualisations to the current "table view". These will allow displaying and browsing the reference codes intuitively. Alternative visualisations should include:
1. alphabetical, hierarchical, as used in https://agrovoc.fao.org/browse/agrovoc/en/index
2. graphs (dendrograms, tree views, or any other suitable representation)

The visualisations should be responsive and as web-accessible as possible. The student should also develop a way to integrate them within the website through, for example, toggles, buttons, options, etc...The visualisations should be integrated into the source code so that they can be easily enabled-disabled.

**Comment by arantzaetxebarria** [comment]
Close this issue as it is similar to https://github.com/ec-jrc/re3gistry/issues/171
