### ISSUE TITLE
Developing an interactive dashboard for the re3gistry manager and authorised users

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#158]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation

# Proposed change
Developing an interactive dashboard for the re3gistry manager and authorised users. The dashboard should be part of the admin space and should help to know at a glance some statistics of the different aspects handled by the re3gistry.
We expect simple and composed counters representing, among others: number of registers available, items by the register, items by status (valid, retired...), number of proposals (not yet public), languages in use (available-missing translations), number of users and available groups.

Counters should allow drilling down to specific details.

The dashboard should be able to export customised PDF reports.

**Comment by jescriu** [comment]
After having analysed this enhancement the JRC INSPIRE team has decided to postpone its potential implementation waiting for the upcoming discussion on the future of the Re3gistry open-source software.
For the above-mentioned reason, this item is temporarily closed.
