### ISSUE TITLE
Change to another Authentification and authorisation identity management

### ISSUE THREAD

**Issue by MartinTuchyna** [ec-jrc/re3gistry#16]
Is it possible to use another Authentification and authorisation identity management service? If yes, where this can be configured?
Thanks, m.

**Comment by df-git** [comment]
Dear Martin,
The Re3gistry 2 integrates [Apache Shiro](https://shiro.apache.org/), that allows different authentication method.
The one implemented in the release of the Re3gistry 2 in the SQL authentication.
Best regards
