### ISSUE TITLE
Priority Data Sets codelist not accessible: "There is a problem in the application"

### ISSUE THREAD

**Issue by oscar9** [ec-jrc/re3gistry#161]
Original [issue ](https://github.com/INSPIRE-MIF/helpdesk-registry/issues/27)

Priority Data Set codelist values are sometimes not displayed in INSPIRE Registry. Following error message was shown around 10.30h (UTC+1).

![149910110-8537dd5c-c3dc-45a7-8030-798eb3e1a6dc](https://user-images.githubusercontent.com/4819782/176148296-d0413463-5a32-4e6c-bc72-710ece82b933.png)

Codelist values are sometimes shown "immediatly" after the request has been sent and sometimes after few seconds.

Could you please tell why this happens?

Steps to reproduce

Try to access https://inspire.ec.europa.eu/metadata-codelist/PriorityDataset several times

**Comment by arantzaetxebarria** [comment]
The original issue has been closed as it seems that is working properly with the new version of INSPIRE Registry.
This issue is therefore closed.
