### ISSUE TITLE
User management interface

### ISSUE THREAD

**Issue by MartinTuchyna** [ec-jrc/re3gistry#17]
Is there an user management graphical interface, which would allow manage users (e.g. invite, create, approve, deactivate, archive, and delete)?

Is it also possible to gropu users into the groups and assign them specific rights/roles?

Thanks, m

**Comment by df-git** [comment]
Dear Martin,
The Re3gistry 2 allows the user management with a user interface. It also allow to create group of users.
Note that the users can be “disabled” but not deleted. All the users are kept to have a traceable history of the registered items. However, if a user is deactivated he will not be able to log in to the system.
Best regards
