### ISSUE TITLE
Overview table contained items - by starting letter

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#171]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Would be nice that in each page where there is a table to be able to see the items by the starting letter of the label.

# Proposed change
would be nice to see them as in the example bellow:
https://data.un.org/Glossary.aspx?d=PopDivG
https://stats.oecd.org/glossary/
https://www.who.int/data/gho/indicator-metadata-registry
https://inspire-regadmin.jrc.ec.europa.eu/dataspecification/CatalogueINSPIREObjects.action

# Additional information
In this way, the contained items could be seen in 3 ways:
1. as a table as it is now
2. by starting letter
3.  by d3.js tree graph (when available)

**Comment by arantzaetxebarria** [comment]
Take into account what is described in https://github.com/ec-jrc/re3gistry/issues/157

**Comment by jescriu** [comment]
After having analysed this enhancement the JRC INSPIRE team has decided to postpone its potential implementation waiting for the upcoming discussion on the future of the Re3gistry open-source software.
For the above-mentioned reason, this item is temporarily closed.
