### ISSUE TITLE
More options for downloading an item 

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#172]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Would be nice to be able to download a register/item after choosing the format/s and the selecting more languages. 

# Proposed change
Add in the formats a custom format or something similar with search page where one can select the item, the formats and the languages in which he should get a compressed folder with the files.

**Comment by jescriu** [comment]
After having analysed this enhancement the JRC INSPIRE team has decided to postpone its potential implementation waiting for the upcoming discussion on the future of the Re3gistry open-source software.
For the above-mentioned reason, this item is temporarily closed.
