### ISSUE TITLE
Register information styled as cards or tiles

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#173]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Register information styled as cards or tiles would be way more appealing using cards

# Proposed change
Could be used this example
[Explain what should be changed in the software. Mockups, screenshots, diagrams
or other graphics are welcome.](https://ec.europa.eu/component-library/playground/ec/?path=/story/components-card--default)

**Comment by jescriu** [comment]
After having analysed this enhancement the JRC INSPIRE team has decided to postpone its potential implementation waiting for the upcoming discussion on the future of the Re3gistry open-source software.
For the above-mentioned reason, this item is temporarily closed.
