### ISSUE TITLE
​Add localization page for the groups

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#174]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Would be nice to be able to add localization for the groups created of newly created.

# Proposed change
Use the existence interface where in each tab there is a language and add localization for the groups.

**Comment by jescriu** [comment]
After having analysed this enhancement the JRC INSPIRE team has decided to postpone its potential implementation waiting for the upcoming discussion on the future of the Re3gistry open-source software.
For the above-mentioned reason, this item is temporarily closed.
