### ISSUE TITLE
Improve the error message when a resource doesnt not exist

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#176]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
A better error message could be included when a resource does not exist: for example 404 message. 
For example: calling an item that doesn't exist  https://example.com/register/item_1 should be shown the message that the item does not exist, not he 404 message.

# Proposed change
Cache the error that the API gives when an item does not exist and shot it in the webapp.

**Comment by arantzaetxebarria** [comment]
Close the issue as it is implemented in https://github.com/ec-jrc/re3gistry/issues/233
