### ISSUE TITLE
History version: add a button or an indication to go the the latest version

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#177]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
When the user is in a version which is not the latest one,  there should be a button or indication to "go to the latest version": (example: https://inspire.ec.europa.eu/glossary/Actor:1), similarly to what Publications Office does
![image](https://user-images.githubusercontent.com/67077116/183492305-3b8505c0-0a74-4bf9-b29f-550febe123fd.png)

# Proposed change
In the webapp add a button or indication to "go to the latest version".

**Comment by arantzaetxebarria** [comment]
1. When you are in the latest version add the link "Last version".
![image](https://github.com/ec-jrc/re3gistry/assets/64014694/9ace396d-3ce7-4387-9648-0111f73d8dc0)

3. When you are on an old version add the link "go to latest version"
 
![image](https://github.com/ec-jrc/re3gistry/assets/64014694/9b6d4a0e-d543-499a-8fcc-61951e045888)
