### ISSUE TITLE
Webapp: login button

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#178]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Would be nice to have a "Login" button in the webapp which could be used by the submitting organization, control body, register/registry manager to go to the management interface.

# Proposed change
Add login button in the upper right corner.

**Comment by unaibrrgn** [comment]
Dear @hernlor, @emanuelaepure10 , as we discussed in the last meeting find below two mockups for possible implementation:

Regards.

![Captura](https://user-images.githubusercontent.com/75972112/230045457-1fd6f695-aba8-43f3-91b8-32e6d6f96f93.PNG)
![captura3](https://user-images.githubusercontent.com/75972112/230045517-63a1a1fe-b0fe-4709-aa8e-5e35d70701ac.PNG)
