### ISSUE TITLE
Show the last modification date attribute

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#179]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Would be nice to see the last modification date attribute in the webapp.

# Proposed change
Get from the API the latest modification date and show it on the webapp

**Comment by iratigarzon** [comment]
Added the last attribute date in the frontend for easier visibility of the latest modifications. This enhancement will be available in [version 2.6.0](https://github.com/ec-jrc/re3gistry/releases/tag/v2.6.0).
