### ISSUE TITLE
Search engine improvement

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#181]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
9.a. the search engine should change behavior so that the results provided are looked in all languages regardless the language selected for the interface. 
9.b. Add a filter by language. this exactly what the EC does in the main page: [example](https://ec.europa.eu/search/?QueryText=ejemplo&op=Search&swlang=en&form_build_id=form-THhJlqWznxDmzes5iBdu_QYEGp0TfleKOYJGMc7unRM&form_id=nexteuropa_europa_search_search_form)
9.c Relatedly, on top of the existing facets ( register, status etc, ) and the language one proposed in 9.b. it would be helpful to include the following to be able to filter by:
•	"versions", in particular to see only "last versions only",
•	filter by internal-externally governed items,
•	modified last week, last month, last year similarly to what EC does with (see link above) and image below
![image](https://user-images.githubusercontent.com/67077116/183494559-5f00cb93-28a0-4743-ae2b-657c3cb3494d.png)

**Comment by arantzaetxebarria** [comment]
take into account issue https://github.com/ec-jrc/re3gistry/issues/141

**Comment by jescriu** [comment]
After having analysed this enhancement the JRC INSPIRE team has decided to postpone its potential implementation waiting for the upcoming discussion on the future of the Re3gistry open-source software.
For the above-mentioned reason, this item is temporarily closed.
