### ISSUE TITLE
Include a pop up window to indicate users the last updates 

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#182]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Include a pop up window to indicate users the last updates on the software level ex:
![image](https://user-images.githubusercontent.com/67077116/183494746-1c14e22f-8c64-4fca-9c50-fd0d1525a5f8.png)

**Comment by jescriu** [comment]
After having analysed this enhancement the JRC INSPIRE team has decided to postpone its potential implementation waiting for the upcoming discussion on the future of the Re3gistry open-source software.
For the above-mentioned reason, this item is temporarily closed.
