### ISSUE TITLE
Integrate Register Federation (Register of Registers - ROR) with the Registry

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#184]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Integrate and publish the code related to Register Federation (Register of Registers - ROR) with the Registry.

# Proposed change

**Comment by unaibrrgn** [comment]
Integrated the Register Federation Tool related code into the project. This code structure is now located inside of the [sources](https://github.com/ec-jrc/re3gistry/tree/master/sources) folder, along with the rest of previously existing projects. [Registry-Federation-Tool](https://github.com/ec-jrc/re3gistry/tree/master/sources/Registry-Federation-Tool).

![image](https://github.com/ec-jrc/re3gistry/assets/75972112/22f39c10-9beb-443c-8af3-9d91d88ac340)
