### ISSUE TITLE
Improve bulk import option so that children are included at once

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#190]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Would be nice to include in the bulk import all the item of the same itemclass with the relations includes, such as parent-child item, item with relation to other register and all in the same file. So the effort for the end user is minimum just to create the import file.  

# Proposed change
Change the bulk import to accept item of the same item class but of different collections.

**Comment by jescriu** [comment]
After having analysed this enhancement the JRC INSPIRE team has decided to postpone its potential implementation waiting for the upcoming discussion on the future of the Re3gistry open-source software.
For the above-mentioned reason, this item is temporarily closed.
