### ISSUE TITLE
Return master language page if a language required/set in your browser doesn't exist

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#192]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
If a certain language is set in the browser and that language doesn't exist in the  system, return the page in the master language , not an error.

**Comment by oruscalleda** [comment]
This issue has been addressed on [#200](https://github.com/ec-jrc/re3gistry/issues/200)
