### ISSUE TITLE
Add a system register from the interface

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#193]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Necessity to have a system register created from the interface, not editing database

# Proposed change
Add a combo box in the page of addition of a register to be able to create from the interface a register which is used just to be linked, but not in the list of the register on the registry page.

**Comment by jescriu** [comment]
After having analysed this enhancement the JRC INSPIRE team has decided to postpone its potential implementation waiting for the upcoming discussion on the future of the Re3gistry open-source software.
For the above-mentioned reason, this item is temporarily closed.
