### ISSUE TITLE
Field type Date error before saving item

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#194]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Be able to add the date from the calendar picker when creating the item.

# Proposed change
The field date is not working when an item is created. First I need to create the item, without filling the date field, than reopen the item and edit it by adding the date  which opens finally the calendar picker.

**Comment by oruscalleda** [comment]
This issues has been fixed and tested, and it's included in the new pre release [2.4.1-rc.1](https://github.com/ec-jrc/re3gistry/releases/tag/v2.4.1-r.1)
