### ISSUE TITLE
Make hyper linkable the group values 

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#196]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Make hyper linkable the group values so that they follow wither the website or email form provided in the groups form

**Comment by iratigarzon** [comment]
Added a hyperlink in the frontend to directly access the website associated with each group. This enhancement will be available in [version 2.6.0](https://github.com/ec-jrc/re3gistry/releases/tag/v2.6.0).
