### ISSUE TITLE
Provide DCAT-AP format at registry and register levels

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#199]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Provide DCAT-AP format at registry and register levels
Take as example RDFFormatter and transform it DCAT-AP format.

**Comment by jescriu** [comment]
After having analysed this enhancement the JRC INSPIRE team has decided to postpone its potential implementation waiting for the upcoming discussion on the future of the Re3gistry open-source software.
For the above-mentioned reason, this item is temporarily closed.
