### ISSUE TITLE
Download codelists in other formats unclear

### ISSUE THREAD

**Issue by thijsbrentjens** [ec-jrc/re3gistry#2]
# Background and Motivation
For a codelist register I'd expect that it is possible to also download/get a full codelist in a specific format, like in RDF+XML or CSV. To me it is unclear how / where to do this and which formats are available (if any other than HTML)..

# Proposed change
Provide links for each format to get the codelist in. For example like in: http://inspire.ec.europa.eu/metadata-codelist/ProtocolValue. And provide a general description how to get resources from the registry. 

# Alternatives
-

# Funding
Not (yet) asked, but could do if needed.

**Comment by MarieLambois** [comment]
I am also interested in the functionality described by Thijs. 

From the "enhancement" tag, I understand that this functionality is not included in the Re3gistry tool but just developed in the INSPIRE codelist registry. Is that correct ? 

Thank you for clarification.

**Comment by geoase** [comment]
I think, xml transformation is to some extent already implemented (format=iso19135xml) in the re3gistry2restapi:
https://github.com/ec-jrc/re3gistry/blob/575d4d7d7554e1583337e387072dffa043493cb5/sources/Re3gistry2RestAPI/src/main/java/eu/europa/ec/re3gistry2/restapi/ItemsServlet.java#L80-L83

There is just no button or direct link in the webapp to retrieve it.


A RDFFormatter Class is there,  but the comment suggests, that there might be some work left to do:
https://github.com/ec-jrc/re3gistry/blob/575d4d7d7554e1583337e387072dffa043493cb5/sources/Re3gistry2RestAPI/src/main/java/eu/europa/ec/re3gistry2/restapi/format/RDFFormatter.java#L47-L50

@df-git 
Maybe I can help to finish the RDF support and add some buttons in the webapp (similar to registry 1.3) if this is needed

**Comment by df-git** [comment]
Dear All,
Thank you for your messages.
The features described above are not yet available in the current release, but they will be released in the following months.

**Comment by df-git** [comment]
Solved in release [v2.1.0](https://github.com/ec-jrc/re3gistry/releases/tag/v2.1.0).
