### ISSUE TITLE
Issue with ecas-tomcat-8.0-4.15.0.jar while building

### ISSUE THREAD

**Issue by yke** [ec-jrc/re3gistry#20]
After you solved https://github.com/ec-jrc/re3gistry/issues/19 I did a GIT pull and saw the POM was updated. The issue 19 is now gone.

However when I do a "clean and build" (from Maven in  NB 11)  i get an error concerning ecas.

```
Failed to execute goal on project Re3gistry2Base: Could not resolve dependencies for project eu.europa.ec:Re3gistry2Base:jar:1.0: Failure to find eu.europa.ec.digit.iam.ecas.client:ecas-tomcat-8.0:jar:4.15.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```
In version1 (march 2020) ecas-tomcat-8.0-3.6.3.jar was created during installation. Now it is not being created and I cannot find it anywhere. I could try to use the old version but I prefer a correct solution.

Do you have any idea ?

**Comment by df-git** [comment]
Thank you for your feedback.
The ecas-tomcat jar needs to be included as a file because the repository is not publicly accessible.
We are working to fix this problem.

**Comment by df-git** [comment]
Dear @yke,
We fixed the issue adding the library as local jar. You need to execute maven "initialize" to initialize your local repository.
