### ISSUE TITLE
Search by language

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#204]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Would be nice to set up the language for the search.
And receive the results in the search languages. 
If no results are available in the search language show the results in master language.

At the moment, for a search the SOLR is looking in all the items and is giving back as well the items which contain the search word in another language than the searched one.

**Comment by arantzaetxebarria** [comment]
Close this issue as it is included in https://github.com/ec-jrc/re3gistry/issues/181
