### ISSUE TITLE
RDF multilingual and ready for geonetwork

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#205]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Create RDF for all the items as it is now in the version 1.3 done only for priority datasets with multilingual version 
See. "[geonetwork ready](https://inspire.ec.europa.eu/registry/res/custompages/PriorityDataset.rdf)" bellow version:

[PriorityDataset.zip](https://github.com/ec-jrc/re3gistry/files/9645981/PriorityDataset.zip)

**Comment by jescriu** [comment]
After having analysed this enhancement the JRC INSPIRE team has decided to postpone its potential implementation waiting for the upcoming discussion on the future of the Re3gistry open-source software.
For the above-mentioned reason, this item is temporarily closed.
