### ISSUE TITLE
Add default fields translations in all 23 official languages in the initialization script of creation of the database

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#212]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Add for the default fields ( label, definition, description, status) in the initialization script of creation-initialization of the database the 23 official languages translation (potentially using an automatic translation service)

**Comment by arantzaetxebarria** [comment]
Take into account issue https://github.com/ec-jrc/re3gistry/issues/113

**Comment by unaibrrgn** [comment]
We added 22 new language translations (English was already working) that can be accesed in the backend via the #286 language selector. The translations may have some errors.
