### ISSUE TITLE
Harmonise the behaviour for all "system lists"

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-jrc/re3gistry#213]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
Add for all the pages of the system the "Available formats", in special for the list status add the "Available formats" that is missing from the interface at this moment.
As status has a special role and different tables, it should be implemented to code that could convert the status into ContainedItems and try to reuse the existent formats

**Comment by jescriu** [comment]
After having analysed this enhancement the JRC INSPIRE team has decided to postpone its potential implementation waiting for the upcoming discussion on the future of the Re3gistry open-source software.
For the above-mentioned reason, this item is temporarily closed.
