### ISSUE TITLE
Upgrade from re3gistry 1.3.1 to 2.3.1 fails

### ISSUE THREAD

**Issue by TeijoKal** [ec-jrc/re3gistry#218]
Tried to upgrade our re3gistry 1.3.1 version to 2.3.1. The following happened:

If i choose to migrate in installation from our existing database the existing data does not correctly appear in version 2.3.1.

Our database in re3gistry 1.3.1 has languages finnish and swedish.
After migration all goes to english. Nothing appears to be seen in finnish or swedish subpages. The migration however managed to distinguish the finnish and swedish languages. And after migration there is three subpages: english, finnish and swedish. But no data in finnish or swedish subpages.

**Comment by oscar9** [comment]
Hi @TeijoKal ,

Thanks for contact us. Our team is going to analyze this issue. Please provide us with any extra information that could be useful for us: tomcat log, error mesages or frontend messages during the migration.

Thanks

**Comment by TeijoKal** [comment]
Here are the log files that was generated during the installation process. No error messages during the installation and normal email about the success of installation.
[catalina.2022-10-11.log](https://github.com/ec-jrc/re3gistry/files/9754278/catalina.2022-10-11.log)
[localhost.2022-10-11.log](https://github.com/ec-jrc/re3gistry/files/9754280/localhost.2022-10-11.log)
[localhost_access_log.2022-10-11.txt](https://github.com/ec-jrc/re3gistry/files/9754282/localhost_access_log.2022-10-11.txt)
[re3gistry2.log](https://github.com/ec-jrc/re3gistry/files/9754289/re3gistry2.log)

**Comment by oscar9** [comment]
Hi @TeijoKal ,

We have seen that there is an issue in your logs that could be the issue to your problem. We will try to replicate this error in our environment.

Thanks

```
[ERROR] 2022-10-11 10:37:50.043 [http-bio-8080-exec-9] [controller.Install.processRequest:131] - Exception occurred in step migration-summary
java.lang.Exception: Attempting to execute an operation on a closed EntityManager.
	at eu.europa.ec.re3gistry2.migration.handler.RegInstallationStepMigrationSummaryHandler.startMigration(RegInstallationStepMigrationSummaryHandler.java:165) ~[Re3gistry2Migration-1.0.jar:?]
	at eu.europa.ec.re3gistry2.migration.handler.RegInstallationStepMigrationSummaryHandler.<init>(RegInstallationStepMigrationSummaryHandler.java:68) ~[Re3gistry2Migration-1.0.jar:?]
	at eu.europa.ec.re3gistry2.web.controller.Install.processRequest(Install.java:129) [Install.class:?]
	at eu.europa.ec.re3gistry2.web.controller.Install.doPost(Install.java:177) [Install.class:?]
```

**Comment by jane-heller-bkg** [comment]
Hi together,

just to state here again, that this issue also comes up in our environment. You will find the log attached. If you need further log files, please just contact me.

Best

Jane

[re3gistry2.migration_bkg.log](https://github.com/ec-jrc/re3gistry/files/9859974/re3gistry2.migration_bkg.log)

**Comment by TeijoKal** [comment]
Do you need data of our environment. I could sent database dump to test

**Comment by oscar9** [comment]
Hi @TeijoKal ,

Thanks for offering your data, it will be very helpful to have another database to test. In any case, just to update you, we have managed to replicate the error and have found some bugs in the migration process that we are dealing with right now related to the handling of identifiers. If it is not a problem for you to share the data base, please contact me by mail and we can talk there, normally a simple dump of the database is enough. omartinez@bilbomatica.es

Best regards

**Comment by oruscalleda** [comment]
Hi,

A solution for this issue has been achieved and we are running tests to verify it's working.

Best regards.
