### ISSUE TITLE
Cache parameter not proper configured

### ISSUE THREAD

**Issue by fabiovinci** [ec-jrc/re3gistry#221]
It seems the `application.cache.disk.path` parameter in the [configuration.properties.orig](https://github.com/ec-jrc/re3gistry/blob/master/dist/app/re3gistry2/WEB-INF/classes/configurations_files/configuration.properties.orig) file contains the sample value "_/path/to/cache_" instead of the variable "`diskcachepath`" contained in the [init.properties](https://github.com/ec-jrc/re3gistry/blob/master/dist/init.properties) file.

Is it correct? Shouldn’t it contain the variable "`diskcachepath`" to be replaced by the `init-config` script?

![image](https://user-images.githubusercontent.com/22212406/195152005-1f3cdedc-79fd-4f8a-ac7f-07a278f3235b.png)

**Comment by oscar9** [comment]
Hi @fabiovinci ,

You are correct. It's already fixed now. That property is new there due to #217 

Thanks for that.
