### ISSUE TITLE
Not working links in the administrator manual

### ISSUE THREAD

**Issue by AntoRot** [ec-jrc/re3gistry#23]
The links "[distribution folder](https://github.com/ec-jrc/re3gistry/blob/master/documentation/dist)" , "[webapp](https://github.com/ec-jrc/re3gistry/blob/master/documentation/dist/webapp)" and "[source](https://github.com/ec-jrc/re3gistry/blob/master/documentation/sources/Re3gistry2RestAPI)" in the [administrator manual](https://github.com/ec-jrc/re3gistry/blob/master/documentation/administrator-manual.md) don't work because the path refers to the current folder (documentation) and not to the parent (i.e. ../) where the folders to link are located.

**Comment by df-git** [comment]
Dear @AntoRot,
Thank you for your feedback. The problem to the links has now been solved.
Kind regards
