### ISSUE TITLE
Update the default error message in the frontend

### ISSUE THREAD

**Issue by oscar9** [ec-jrc/re3gistry#233]
# Background and Motivation

The error message should be updated to a more updated message related to the actual workflow.
![image](https://user-images.githubusercontent.com/4819782/199462926-c39ef6f6-7741-4f3a-8992-1a647eb1856b.png)

# Proposed change

Change the message to the corresponding helpdesk and not to the JRC email.

**Comment by unaibrrgn** [comment]
The issue has been solved and tested in our local environment.
