### ISSUE TITLE
Search error when fields are missing in Solr

### ISSUE THREAD

**Issue by oscar9** [ec-jrc/re3gistry#234]
When a Re3gistry instance is low in data an error could occur in the frontend when a search is executed.

![image](https://user-images.githubusercontent.com/4819782/199463829-5a3f9ee5-6a5b-4d56-a09d-3e294b5b967f.png)

- The error happens when the instance has no item or items with an empty description. 
- This causes solr not to create fl_label_description fields and the search is dependent on those fields. Also, when the field is empty Solr ignores that insert and the field is not created. 
- The search is created in the frontend.

**Comment by oruscalleda** [comment]
This issue has been solved and tested, the changes are in the new pre release [2.4.1-rc.1](https://github.com/ec-jrc/re3gistry/releases/tag/v2.4.1-r.1)
