### ISSUE TITLE
Atom format content type is set to "text/xml"

### ISSUE THREAD

**Issue by oscar9** [ec-jrc/re3gistry#236]
Atom format content type is set to "text/xml" in the class AtomFormatter getContentType method. This content type should be "text/atom+xml" as is use in different parts of the Re3gistry software.

**Comment by oruscalleda** [comment]
This issues has been resolved in [235/236](https://github.com/ec-jrc/re3gistry/tree/235/236-AvailableFormatsUtil-not-containing-all-formats)
