### ISSUE TITLE
Incorrect status code when accessing a page that does not exist

### ISSUE THREAD

**Issue by arantzaetxebarria** [ec-jrc/re3gistry#242]
It has been detected through the INSPIRE Validator ([issue 883](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/883)), that when accessing an INSPIRE Registry item that does not exist, the request returns a 200, when it should return a 404 error code.

https://inspire.ec.europa.eu/codelist/SpecificExposedElementTypeValue/soilErosion

![2022-12-20_11h17_39](https://user-images.githubusercontent.com/64014694/208646224-338e4d7c-1414-4235-843c-9161a8adecd9.png)

Note: The API is giving a 404 error code.

![2022-12-20_11h19_43](https://user-images.githubusercontent.com/64014694/208646343-577fa5c5-9e60-4a15-89d9-2bd585968eee.png)

**Comment by juanpelegrina** [comment]
after a deep analysis of this issue, we can concluce that solving this issue implies a new redesign of how the front treats the responses from the back.

**Comment by arantzaetxebarria** [comment]
Dear community

In order to correct this situation, a solution has been implemented from INSPIRE Validator side, in [issue 963](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/963)  is the detailed explanation, thanks.

Best regards
