### ISSUE TITLE
DataTables warning popup when clicking manage content

### ISSUE THREAD

**Issue by jorgejesus** [ec-jrc/re3gistry#25]
DataTables warning popup when clicking manage content

- [ x ] a description of the steps to reproduce your issue

Clicking on `Content` icon on top tool bar it outputs an DataTables warning and is not certain if it works properly. 

- [ x ] the browser and version used

Firefox 80.0.1 Linux

- [ x ] a screenshot illustrating the problem

![image](https://user-images.githubusercontent.com/1275400/93198091-cc934480-f74c-11ea-8b05-9c62a666ce43.png)

- [ x ] the URL of your service / the file you have uploaded or referenced (as
an attachment).

https://re3gistry.isric.org/re3gistry2

This is a testing service,  I can provide the login for testing debug, gitter: @jorgejesus

**Comment by df-git** [comment]
Solved in release [v2.1.0](https://github.com/ec-jrc/re3gistry/releases/tag/v2.1.0).
