### ISSUE TITLE
Codelist iso19135 format missing the <status> element for each entry

### ISSUE THREAD

**Issue by arantzaetxebarria** [ec-jrc/re3gistry#250]
This issue comes from INSPIRE Registry helpdesk #[45](https://github.com/INSPIRE-MIF/helpdesk-registry/issues/45)
From: [OTWillems](https://github.com/OTWillems)

> An FME application I developed for Dutch local government checks in a codelist if an entry is still valid. My logic can't determine if an entry is valid because the status node is missing in the ISO 19135 format.
> 
> INSPIRE Registry Codelist that has the issue:
> https://inspire.ec.europa.eu/codelist/EnvironmentalDomain
> 
> INSPIRE codelist as ISO 19135
> https://inspire.ec.europa.eu/codelist/EnvironmentalDomain/EnvironmentalDomain.en.iso19135xml
> 
> The ISO 19135 XSD it's referring to:
> https://standards.iso.org/iso/19135/-2/reg/1.0/registration.xsd#:~:text=%3CcomplexType%20name%3D%22RE_RegisterItem_Type,%3C/complexType%3E
> 
> The part of the XSD stating that status is mandatory:

> ```
> <complexType` name="RE_RegisterItem_Type">
> <complexContent>
> <extension base="pre:Abstract_RegisterItem_Type">
> <sequence>
> <element maxOccurs="unbounded" minOccurs="0" name="predecessor" type="reg:RE_RegisterItem_PropertyType"/>
> <element name="itemIdentifier" type="gco:Integer_PropertyType"/>
> <element name="name" type="gco:CharacterString_PropertyType"/>
> <element name="status" type="reg:RE_ItemStatus_PropertyType"/>              <<<<=========
> <element minOccurs="0" name="dateAccepted" type="gco:Date_PropertyType"/>
> <element minOccurs="0" name="dateAmended" type="gco:Date_PropertyType"/>
> ...
> </sequence>
> </extension>
> </complexContent>
> </complexType>
> ```

**Comment by OTWillems** [comment]
Hello,
I see this item is marked as closed, but I don't see any changes in the ISO19135 codelist, could you provide some feedback on the status? (pun intended)

**Comment by PB-GNM** [comment]
Hello,

We see the problem is still existing, so, we would like you to reopened it.

Example:
https://inspire.ec.europa.eu/codelist/Natura2000DesignationValue/proposedSiteOfCommunityImportance
No status in the iso19135xml output:
https://inspire.ec.europa.eu/codelist/Natura2000DesignationValue/proposedSiteOfCommunityImportance/proposedSiteOfCommunityImportance.nl.iso19135xml
But there is one in the json output:
https://inspire.ec.europa.eu/codelist/Natura2000DesignationValue/proposedSiteOfCommunityImportance/proposedSiteOfCommunityImportance.nl.json

**Comment by boerss** [comment]
This issue is important to us (Bij12) as we use the ISO 19135xml format to automatically detect & process codelistupdates for only valid codelists! Without this being solved we validate our INSPIRE data against outdated codelists!

Thanx for your attention.
