### ISSUE TITLE
Make the version of the software a propery to ease it's change each release

### ISSUE THREAD

**Issue by oruscalleda** [ec-jrc/re3gistry#266]
# Background and Motivation
The software version doesn't get updated easily right now.

# Proposed change
Make the version a configuration property to make it easier to change it on each release.

**Comment by iratigarzon** [comment]
Added a property **application.version.code** to the **configuration.properties** file for easier version management. This enhancement will be available in [version 2.6.0](https://github.com/ec-jrc/re3gistry/releases/tag/v2.6.0).
