### ISSUE TITLE
 Force to change the password for the first time

### ISSUE THREAD

**Issue by arantzaetxebarria** [ec-jrc/re3gistry#267]
# Background and Motivation
Currently, once you click the link to activate your account, it redirects you to a page on the Re3gistry management site that tells you if your user has been successfully activated. 
![image](https://user-images.githubusercontent.com/64014694/227192945-8a58cc82-8a70-4670-9283-bea63192edac.png)

# Proposed change

The idea is to **force a change of password for the first time**, to make the system more secure.

Note: It would also require a change in the activation email sent to the registered user “For security reasons, you will be asked to change the password after first sign in. ”

**Comment by iratigarzon** [comment]
To enhance security when creating new users, a new page has been developed where you are prompted to change the password received via email the first time before being able to access the Re3gistry.

![changePassword](https://github.com/ec-jrc/re3gistry/assets/127838239/5851dc5d-1b09-4ed8-aa02-932f85d08ad5)
