### ISSUE TITLE
When publishing an item, send an email to all those who have participated in the process.

### ISSUE THREAD

**Issue by arantzaetxebarria** [ec-jrc/re3gistry#268]
# Background and Motivation
The motivation is to let them know that the item is not only accepted but public, closing the change proposal lifecycle

# Proposed change
Send a notification to everyone who has been involved in the process of **publication** for a determined item

**Comment by iratigarzon** [comment]
Improved the email service to send notifications to all users who have participated in the process. This enhancement will be available in version [2.6.0](https://github.com/ec-jrc/re3gistry/releases/tag/v2.6.0).
