### ISSUE TITLE
Using of PostgreSQL-Schema

### ISSUE THREAD

**Issue by mattenp** [ec-jrc/re3gistry#27]
Hi,

i would like to use a different dbschema, not the public schema, like here https://jdbc.postgresql.org/documentation/head/connect.html , currentSchema parameter in JDBC.

Best regards,

Matthias

**Comment by df-git** [comment]
Dear @mattenp,
To use a different schema, (if all your entities are on the same schema) you can try to use the XML mapping file as explained here: https://stackoverflow.com/questions/3211138/jpa-eclipselink-how-to-change-default-schema.

Best regards,
Daniele on behalf of the INSPIRE support team
