### ISSUE TITLE
Chance page icons (Favicon) to point to our own repository and images

### ISSUE THREAD

**Issue by unaibrrgn** [ec-jrc/re3gistry#277]
# Background and Motivation
The current favicons that are used are from the European Union and the links point to a different repository.

# Proposed change
Have our favicons on a repository of our own.

**Comment by iratigarzon** [comment]
The developer manual, located at 'documentation/developer-manual.md', has been revised to provide instructions on updating the URLs for Page Icons (Favicons) and Images. This updated documentation will be included in the upcoming release, version 2.6.0.
