### ISSUE TITLE
Implement Unit testing

### ISSUE THREAD

**Issue by oruscalleda** [ec-jrc/re3gistry#279]
# Background and Motivation
"Bulletproof" the Re3gistry and make future development safer.

# Proposed change
Implement unit testing on the application.

**Comment by jescriu** [comment]
After having analysed this enhancement the JRC INSPIRE team has decided to postpone its potential implementation waiting for the upcoming discussion on the future of the Re3gistry open-source software.
For the above-mentioned reason, this item is temporarily closed.
