### ISSUE TITLE
CSV bulk import of second-level items seen as first-level items?

### ISSUE THREAD

**Issue by fhb1990** [ec-jrc/re3gistry#28]
I am setting up a codelist register. My content structure is as below.

![classes](https://user-images.githubusercontent.com/34007375/95097992-69367a00-072e-11eb-8657-9a37f061531a.PNG)

```Codelijst``` is the codelist register, ```Codelijst-item``` are the codelists themselves, and ```Codelijstwaarde``` are the codelist values.

I am trying to do a bulk import of a csv containing codelist values for one specific codelist. As can be seen in the screenshot below, I press the ```Bulk import``` button, while on the content page of the codelist.

![bulkimport](https://user-images.githubusercontent.com/34007375/95098364-e4982b80-072e-11eb-9159-a1752ef6cfbf.PNG)

I try to add the following codelist value (just one, for testing purposes):

![csv](https://user-images.githubusercontent.com/34007375/95098551-1d380500-072f-11eb-9b6d-efef8ba997b3.PNG)

The upload is succesful. However, when I check the action in the ```Submitting organisations``` tab, I can see that the item is added at the codelist level, and not as a codelist value.

![resultaat](https://user-images.githubusercontent.com/34007375/95098655-40fb4b00-072f-11eb-8294-237189e73de0.PNG)

The item is also not added in the ```New items proposed``` section, neither at the codelist nor at the codelist value level.

Am I right to expect that I should be able to import codelist values in this manner? Could someone explain whether something is wrong with my workflow?

Thanks in advance.

**Comment by MarieLambois** [comment]
I have exactly the same issue with this structure (very similar) : 
![image](https://user-images.githubusercontent.com/12797943/96248273-9515f300-0fab-11eb-9b36-daa6384e77f8.png)
Note that when I download the template, this is the template of the appropriate level.

**Comment by df-git** [comment]
Solved in release [v2.1.0](https://github.com/ec-jrc/re3gistry/releases/tag/v2.1.0).
