### ISSUE TITLE
Version 2.4.2 installation problem

### ISSUE THREAD

**Issue by TeijoKal** [ec-jrc/re3gistry#288]
Tried to install version 2.4.2 webapp part. Intalled in Redhat 9 server.

First installed Apache httpd. Server version: Apache/2.4.53 (Red Hat Enterprise Linux).

Then took the file httpd.conf from the installation package and copied it to directory /var/httpd/conf and also file httpd-vhosts.conf in the directory /var/httpd/conf/extra.

Then trying to start the httpd caused only error. It seemed that in the Redhat installation there are not all modules included in httpd.conf file.

sudo yum install mod_proxy_html
Helped to include the missing modules. But the problem is now (in httpd.conf):

# Configure mod_proxy_html to understand HTML4/XHTML1
<IfModule proxy_html_module>
Include conf/extra/proxy-html.conf
</IfModule>
 
Where can i find this proxy-html.conf file??

**Comment by oruscalleda** [comment]
Hi @TeijoKal, sorry to hear that. 

Right now I don't think we have that specific file, but we'll take a look on this issue and try to get a solution as soon as possible.

**Comment by iratigarzon** [comment]
Dear @TeijoKal,

Since this issue pertains to an older version of the app, we recommend installing the latest version. If you continue to experience this issue, please open a new ticket.

Best regards,

Irati
