### ISSUE TITLE
Re3gistry 2.4.2 webapp installation problem

### ISSUE THREAD

**Issue by TeijoKal** [ec-jrc/re3gistry#289]
Started to install the version 2.4.2 webapp part. Read the instructions and it is telling the following

### Install the web-app configuration file in xampp
1. Paste the example configuration file `re3gistry2-webapp.conf` in `<xamp_root>\apache\conf\extra`

Now the question is that where that re3gistry2-webapp.conf can be found?? The file is not found in the installation package.

**Comment by oruscalleda** [comment]
Hi @TeijoKal the file is in this folder Re3gistry2ServiceWebapp\support_files
![image](https://github.com/ec-jrc/re3gistry/assets/116353060/22ab66ff-9600-40da-980a-2d5a0e9a0df2)
 In case you don't have the file you can download it from [here](https://github.com/ec-jrc/re3gistry/tree/master/sources/Re3gistry2ServiceWebapp/support_files)
