### ISSUE TITLE
Library upgrades

### ISSUE THREAD

**Issue by arantzaetxebarria** [ec-jrc/re3gistry#291]
The following libraries need to be updated, they are outdated or contain other critical vulnerabilities

•    Apache Tomcat 7.0.76 (julkaistu 9.3.2017) 
•    PHP 5.4.16 (julkaistu 6.6.2013) 
•    Apache 2.4.6 (julkaistu 15.6.2013) 
•    OpenSSL 1.0.2 
•    Jquery-ui 1.11.4 

The recommendation is to update the components. 
 
In addition, Re3girstry software also uses these, which contain vulnerabilities: 
-    log4-1.217.jar 
-    zip4j-1.3.2.jar 
-    jdom-1.1-jar 
-    jstl-1.2.jar 
-    mail-1.4.7.jar

**Comment by oruscalleda** [comment]
All libraries have been updated without any issues.
