### ISSUE TITLE
Improve the functionality of the creation of hyperlinked fields

### ISSUE THREAD

**Issue by arantzaetxebarria** [ec-jrc/re3gistry#292]
Improve the functioning of the creation of hyperlinked fields
![image](https://github.com/ec-jrc/re3gistry/assets/64014694/c6725a09-e869-4056-b61a-f481197e8798)

E.g.
When creating an item, the "ReferenceLink" field contains only 1 field to fill in. 
![image](https://github.com/ec-jrc/re3gistry/assets/64014694/215b1b42-9a5c-4e99-b64c-b374e1232a4a)

Once it is saved, in the form it appears with 2 fields (Value and Link).
![image](https://github.com/ec-jrc/re3gistry/assets/64014694/47ae1e2f-cfc6-4744-82fc-219f8f23a069)

A new issue will be created to see the behaviour of this type of field.
![image](https://github.com/ec-jrc/re3gistry/assets/64014694/c6725a09-e869-4056-b61a-f481197e8798)

It should be possible to enter the values Value and Link from the creation functionality (taking into account the **bulk import** update). Also take into account the **multivalued** option when implementing the solution

**Comment by iratigarzon** [comment]
This issue has been reviewed and fixed. It will be available in the upcoming release, version 2.5.3.
