### ISSUE TITLE
Date field value

### ISSUE THREAD

**Issue by matejsot** [ec-jrc/re3gistry#3]
I can input any (string) value to a date field.

How I got to the bug:
I created a new register item. This item has also a date field. While inserting values I can put any string in the date field (for example: "aaa"). When I am in the date field the calendar where I can choose a date isn't shown. I can confirm such value and save the item.

When I edit this same item and I enter the date field, the calendar is shown but I can still input any string in this field.

I believe this is not an expected behavior. I used Firefox and Edge.

**Comment by df-git** [comment]
Dear @matejsot,
It was difficult to replicate the problem (we are always getting the calendar picker on dates field)
However, we changed something and we published the solution on the test-bed.
Can you please check if it is now fine?

**Comment by matejsot** [comment]
The problem is still present. 
The behaviour is the same.

**Comment by df-git** [comment]
Can you please give more context? We cannot reproduce this problem.
We tried to insert "non date" text but it is always reduced to a date.
Thank you in advance.

**Comment by matejsot** [comment]
Attached is the record of my desktop. I get the same behaviour on my work and home laptop and wether I use Firefox, Chrome or Edge. The recording was done on Firefox 74. If you need some more information, please specify.

[Re3gistry 2 - Reference codes management system - Mozilla Firefox 2020-04-06 09-45-00.zip](https://github.com/ec-jrc/re3gistry/files/4436829/Re3gistry.2.-.Reference.codes.management.system.-.Mozilla.Firefox.2020-04-06.09-45-00.zip)

**Comment by df-git** [comment]
Dear Matej,
Thank you for sharing the screen recording. We applied the fix. Can you please check the system now?

**Comment by matejsot** [comment]
Now it works fine. Thanks.
