### ISSUE TITLE
Write permission for configuration_files folder

### ISSUE THREAD

**Issue by AntoRot** [ec-jrc/re3gistry#30]
After installing the Re3gistry 2 core app (i.e. re3gistry2 and re3gistry2restapi), following the steps described in the [administrator manual](https://github.com/ec-jrc/re3gistry/blob/master/documentation/administrator-manual.md) (i.e. configuration and launch of init.properties script, customization of the application's configuration files, database setup, copy of the 2 apps in the tomcat webapps folder), I started the installation wizard filling all information required and choosing the migration option.

The migration failed but no error message was shown neither I received a notification by email.
Then I tried again choosing the installation option and this time the error message "Permission denied" appeared. Thanks to the support of the Re3gistry team, I realized that this meant that the [```configuration_files```](https://github.com/ec-jrc/re3gistry/tree/master/dist/app/re3gistry2/WEB-INF/classes/configurations_files) folder shall have the write permission.

Please add this important information in the administrator manual.

Moreover, a more explanatory error message should be shown also in case of the migration option.

**Comment by df-git** [comment]
Solved in release [v2.1.0](https://github.com/ec-jrc/re3gistry/releases/tag/v2.1.0).
