### ISSUE TITLE
Add a loading bar for long processes

### ISSUE THREAD

**Issue by oruscalleda** [ec-jrc/re3gistry#303]
# Background and Motivation
Add a loading bar, loading circle or some visual aid to let the user know something is being processed (bulk import and recache)

# Proposed change
Add a loading bar when a long process is being executed.

**Comment by unaibrrgn** [comment]
Two new loading animations have been added to the re3gistry2 software. First one appears when bulk importing data to an existing register. This animation is played until the process has finished and the page finally reloads. 
![image](https://github.com/ec-jrc/re3gistry/assets/75972112/f5aa0146-f1f3-479a-b110-6b39109dad43)
![image](https://github.com/ec-jrc/re3gistry/assets/75972112/b2aeeaef-ee2f-4912-83cd-428523cdee48)

**Comment by unaibrrgn** [comment]
This animation has also been included in the process of running full cache of the application and running the app's full solar indexing.
![image](https://github.com/ec-jrc/re3gistry/assets/75972112/4838a96a-bd7f-4932-8c0f-3ab9aecf85e9)
