### ISSUE TITLE
New users don't get E-mail

### ISSUE THREAD

**Issue by PB-GNM** [ec-jrc/re3gistry#305]
As a registry manager of http://inspirelab.geonovum.nl:8080/re3gistry2, I can make new users.

But they don't receive an E-mail with their password.

When using: http://inspirelab.geonovum.nl:8080/re3gistry2/resetPassword
It returns an error that the user is not in the database even when I'm sure it is in the users list.
This also happens to users that have been created 1 year ago.

What could be wrong?

Best regards,
Pieter

**Comment by oruscalleda** [comment]
Hi Peter,

I'm sorry to hear about your problems, can I ask you a few questions?

- Is user creation the only emails not being sent?
- Have you tried to activate the user manually in the database?
- Has the reg_user_codes table been updated with codes for each user?

If your reg_user_codes has data, you can manually assemble the link to activate the user with __registryURL__/activate?code=__activation_code__ (you can get __activation_code__ from the reg_user_codes table by the "activation" action)

I hope this resolves your immediate issues, once we get the questions answered we we'll try to give you more info.

Thank you,
Oriol

**Comment by PB-GNM** [comment]
Hi Oriol,

Thank you for the answer.
I will try to answer your counter questions below.

- Is user creation the only emails not being sent? --> Also when changes are made to existing users, like a new role, they don't get an e-mail notification.
- Have you tried to activate the user manually in the database? --> I don't know how to access the database and how to activate users manually.
- Has the reg_user_codes table been updated with codes for each user? --> I don't know how to check this and where to find this table, because  I don't know how to access the database.

Best regards,
Pieter

**Comment by rkaesehagen** [comment]
Hi Pieter, this one is solved. The mail was sent using the O365 credentials of a former employee. After he left, the mailaccount was disabled and thusm ail was not sent anymore.
