### ISSUE TITLE
Migrating re3gistry2 to new server / ssl secured

### ISSUE THREAD

**Issue by rkaesehagen** [ec-jrc/re3gistry#307]
Dear team,

I am migrating a re3gistry2 instance 2.0.0 to a new environment 2.5.0. 
- Tomcat 9 SSL
- Postgres 9.6
- SOLR 8.6  (SSL)
- Frontend with SSL

I exported the old 2.0.0 database to the new server, changed the URLS in the database. Now the backend is accessible, uers can login and the registry content is visible. Emails are sent, caching process works, so all fine.

The problem is, that the frontend is not working. When I access the restapi with the url /registry/rest i get the following response:
{
  "error" : {
    "code" : 400,
    "description" : "Either uri or uuid query parameter required",
    "description-code" : "bad-request"
  }
}
The frontend error: The element requested has not been found in the system. If you think this could be an error, you can .

Any clues or tips how to make the frontend working?

Regards Rob

**Comment by unaibrrgn** [comment]
Dear @rkaesehagen, 
Thanks for reporting the issue, an analysis is being done. We will keep you informed with our discoveries, and we will try to provide a more developed answer as soon as possible. The first thing I can see is that your not accessing the restapi correctly.

To access the different items and see the results inside of the restapi you should use a proposal of this kind:

You can either access the items by their URI value or their UUID.

http://XXXXXXX/registry/rest?uri=XXX&lang=XX&format=jsonc
http://XXXXXXX/registry/rest?uuid=XXX&lang=XX&format=jsonc

Regards,
Unai.

**Comment by rkaesehagen** [comment]
Hi Unnai,
Thanks for your suggestion. This was very helpful.
https://test.inspireregister.nl/registry/rest?uuid=1649423e600dbd7b4958b43acf40806c&lang=nl&format=jsonc 

Gives the correct output. The question is now how to show the output in the frontend. I installed the sample frontend, but this gives no output, except the previously mentioned error. 

Thanks for your help!

**Comment by rkaesehagen** [comment]
Hi,
i did some extra research: When I enter https://test.inspireregister.nl/codelijst/BoreholePurposeValue/miningResearch in the browser it works. I can clik on other links and they are opening fine. I follow the breadcrumb until the "root" level. 

So https://test.inspireregister.nl/codelijst / https://test.inspireregister.nl/registry gives an error, 

Itm us be something really tiny in the settings or configuration.

**Comment by rkaesehagen** [comment]
I found the problem. The postgres import of the old environment was not succesful. One record was missing.
