### ISSUE TITLE
RelationReference fields can't be properly updated

### ISSUE THREAD

**Issue by arantzaetxebarria** [ec-jrc/re3gistry#312]
This error happens when updating the information on a RelationReference type field.
If the user removes the value and selects a new one, the Registry creates a draft with the edited version. This draft has the correct information, but when approving the changes to turn it into Valid state, and publish the item, both the old relation and the new one proposed appear in the administration tool and in the Front end.

### How to reproduce
Here's an example illustrated by screenshots to help me explain the issue.
This item has the Application Schema field, which is of type RelationReference.
![image](https://github.com/ec-jrc/re3gistry/assets/64014694/e43e8504-7176-442d-804a-53a441998248)

Now. the Application Schema field is updated.
![image](https://github.com/ec-jrc/re3gistry/assets/64014694/0251862f-7c9e-43e7-bd00-1f4be163965f)

After clicking on "Accept clarification" a draft is created.
![image](https://github.com/ec-jrc/re3gistry/assets/64014694/0adeb353-2960-4351-920e-eaf7c431d4d9)

Now, after approving the changes instead of replacing the information with the new one, both appear.
![image](https://github.com/ec-jrc/re3gistry/assets/64014694/54b1212f-3725-4870-b376-82a8892b2ca8)

**Note**: this bug has been reproduced in version v2.3.0

**Comment by EnekoRuiz** [comment]
Implemented code so the item's old relations are correctly removed. The problem was that when changing the value of the relation the new one was stored but the old one was never deleted.
