### ISSUE TITLE
Bulk Import / Edit - Create options for each functionality

### ISSUE THREAD

**Issue by arantzaetxebarria** [ec-jrc/re3gistry#315]
Currently, only one button called "bulk import" groups the two possibilities (edit and import). 
Ideally, it would be better to differentiate the possibilities so as not to mislead the user.
The idea is to separate these options and to make the error messages specific to each function.

**Comment by unaibrrgn** [comment]
Separated bulk import and edit to 2 separate items into the same action selector where the previous bulk import button was located. Each of the functionalities has its own menu popup menu.

![image](https://github.com/ec-jrc/re3gistry/assets/75972112/2728b1fd-2373-41d0-80ad-aa87db86003e)
![image](https://github.com/ec-jrc/re3gistry/assets/75972112/2b784419-a02b-4b8f-87d8-91d807e59782)
![image](https://github.com/ec-jrc/re3gistry/assets/75972112/c6fca19d-5451-4a17-8391-d3cbbeb75f30)
![image](https://github.com/ec-jrc/re3gistry/assets/75972112/452ab5b1-7fc1-4a92-9400-0e9d08347ae1)
