### ISSUE TITLE
Where to find descriptor metadata files?

### ISSUE THREAD

**Issue by fhb1990** [ec-jrc/re3gistry#32]
I have set up the codelist register for NL. I am trying to generate the descriptor metadata files, so I can link our registry/registers to the RoR.

If I understand the user documentation correctly, these metadata files will be exposed when I set the 'Register Federation export' flag to 'On', as below.

![image](https://user-images.githubusercontent.com/34007375/103009459-1acb9700-4537-11eb-86dd-95d67999aa73.png)

However, how do I access this export? I don't know where to look for the data.

**Comment by df-git** [comment]
Solved in release [v2.1.0](https://github.com/ec-jrc/re3gistry/releases/tag/v2.1.0).
