### ISSUE TITLE
Front-end is bugged or i did something wrong?  I have followed administrator-manual.md

### ISSUE THREAD

**Issue by k-eight-v** [ec-jrc/re3gistry#322]
![image](https://github.com/ec-jrc/re3gistry/assets/129046182/50e03bc7-2368-45bd-a506-71681c45ed58)

**Comment by k-eight-v** [comment]
Here is default index.xml, icons wont work, and restapi gives me this error. 

HERE IS MY HTTPD conf: 

<VirtualHost *:80>
        ServerName re3gistrytest.sise.envir.ee
        ServerAdmin help@kemit.ee
        RewriteEngine On
        RewriteCond %{HTTPS} off
        RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R,L]
        LogLevel info
        ErrorLog     /var/log/httpd/re3gistry2-error.log
        CustomLog    /var/log/httpd/re3gistry2-access.log combined
</VirtualHost>

<VirtualHost *:443>
        ServerName re3gistrytest.sise.envir.ee
        ServerAdmin help@kemit.ee

        SSLEngine on
        SSLCertificateFile    /etc/httpd/certs/wild.sise.envir.ee.crt
        SSLCertificateKeyFile /etc/httpd/certs/wild.sise.envir.ee.key
        #SSLCertificateChainFile /etc/httpd/certs/gd_bundle-g2-g1.crt

        DocumentRoot "/opt/app/re3gistry2webapp/public_html"
        <Directory "/opt/app/re3gistry2webapp/public_html">
                AllowOverride All
                Options -Indexes -FollowSymLinks
                Require all granted
        </Directory>

        BrowserMatch ".*MSIE.*" nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0
        CustomLog    /var/log/httpd/re3gistry2-ssl-access.log combined
        ErrorLog     /var/log/httpd/re3gistry2-ssl-error.log

        ## Alias for the /registry path
        Alias /registry "/opt/app/re3gistry2webapp/public_html"

        ProxyPreserveHost Off

        ## Proxy to expose the Re2gistry 2 management interface
        ProxyPass /re3gistry2 http://localhost:8080/re3gistry2
        ProxyPassReverse /re3gistry2 http://localhost:8080/re3gistry2

        ## Proxy to expose the Re2gistry 2 rest API
        ProxyPass /registry/rest http://localhost:8080/re3gistry2restapi/items/any Keepalive=On
        ProxyPassReverse  /registry/rest http://localhost:8080/re3gistry2restapi/items/any Keepalive=On

        ## Proxypass to expose the Re3gistry 2 Solr instance (select)
        ProxyPass /registry/searchapi http://localhost:8983/solr/re3gistry2/select Keepalive=On
        ProxyPassReverse /registry/searchapi http://localhost:8983/solr/re3gistry2/select Keepalive=On


        ### Rewrite rules ###
        RewriteEngine on

        ## Handling direct request to a file
        RewriteCond %{REQUEST_URI} !^/registry/js
        RewriteRule ^/(.*)/(.*)\.([a-z]{2})\.(json|xml|atom|csv|rdf|iso19135xml)$ %{REQUEST_SCHEME}://%{HTTP_HOST}/registry/rest?lang=$3&uri=http://%{HTTP_HOST}/$1&format=$4 [L]

        ## Handling content negotiation: json
        RewriteCond %{REQUEST_URI} !^/registry/rest
        RewriteCond %{HTTP_ACCEPT}  ^application/json$
        RewriteCond %{HTTP:Accept-Language} ([a-z]{2}) [OR]
        RewriteCond %{HTTP:Accept-Language} ^()$
        RewriteRule ^/(.*) %{REQUEST_SCHEME}://%{HTTP_HOST}/registry/rest?lang=%1&uri=http://%{HTTP_HOST}/$1&format=json [P,L]

        ## Handling content negotiation: iso19135xml
        RewriteCond %{REQUEST_URI} !^/registry/rest
        RewriteCond %{HTTP_ACCEPT}  ^application/x-iso19135+xml$
        RewriteCond %{HTTP:Accept-Language} ([a-z]{2}) [OR]
        RewriteCond %{HTTP:Accept-Language} ^()$
        RewriteRule ^/(.*) %{REQUEST_SCHEME}://%{HTTP_HOST}/registry/rest?lang=%1&uri=http://%{HTTP_HOST}/$1&format=iso19135xml [P,L]

        ## Handling content negotiation: re3gistry xml
        RewriteCond %{REQUEST_URI} !^/registry/rest
        RewriteCond %{HTTP_ACCEPT}  ^application/xml$
        RewriteCond %{HTTP:Accept-Language} ([a-z]{2}) [OR]
        RewriteCond %{HTTP:Accept-Language} ^()$
        RewriteRule ^/(.*) %{REQUEST_SCHEME}://%{HTTP_HOST}/registry/rest?lang=%1&uri=http://%{HTTP_HOST}/$1&format=xml [P,L]

        ## Handling content negotiation: atom
        RewriteCond %{REQUEST_URI} !^/registry/rest
        RewriteCond %{HTTP_ACCEPT}  ^application/atom+xml$
        RewriteCond %{HTTP:Accept-Language} ([a-z]{2}) [OR]
        RewriteCond %{HTTP:Accept-Language} ^()$
        RewriteRule ^/(.*) %{REQUEST_SCHEME}://%{HTTP_HOST}/registry/rest?lang=%1&uri=http://%{HTTP_HOST}/$1&format=atom [P,L]

        ## Handling content negotiation: atom
        RewriteCond %{REQUEST_URI} !^/registry/rest
        RewriteCond %{HTTP_ACCEPT}  ^application/rdf+xml$
        RewriteCond %{HTTP:Accept-Language} ([a-z]{2}) [OR]
        RewriteCond %{HTTP:Accept-Language} ^()$
        RewriteRule ^/(.*) %{REQUEST_SCHEME}://%{HTTP_HOST}/registry/rest?lang=%1&uri=http://%{HTTP_HOST}/$1&format=rdf [P,L]

        ## Handling content negotiation: atom
        RewriteCond %{REQUEST_URI} !^/registry/rest
        RewriteCond %{HTTP_ACCEPT}  ^text/csv$
        RewriteCond %{HTTP:Accept-Language} ([a-z]{2}) [OR]
        RewriteCond %{HTTP:Accept-Language} ^()$
        RewriteRule ^/(.*) %{REQUEST_SCHEME}://%{HTTP_HOST}/registry/rest?lang=%1&uri=http://%{HTTP_HOST}/$1&format=csv [P,L]

        ## Generic request to the registry
        RewriteCond %{REQUEST_URI} !^/re3gistry2
        RewriteCond %{REQUEST_URI} !^/registry/searchapi
        RewriteCond %{REQUEST_URI} !^/registry/search
        RewriteCond %{REQUEST_URI} !^/registry/rest
        RewriteCond %{REQUEST_URI} !^/registry/index\.html
        RewriteCond %{REQUEST_URI} !^/registry/js
        RewriteCond %{REQUEST_URI} !^/registry/css
        RewriteCond %{REQUEST_URI} !^/registry/img
        RewriteCond %{REQUEST_URI} !^/registry/conf
        RewriteCond %{REQUEST_URI} !^/registry/libs
        RewriteCond %{REQUEST_URI} !index\.html$
        RewriteCond %{REQUEST_URI} !\.json$
        RewriteRule ^/(.*) /index.html [L]


        ## Handling search requests
        RewriteCond %{REQUEST_URI} !^/registry/searchapi
        RewriteRule ^/registry/search(.*) /search.html$1 [L]

</VirtualHost>

**Comment by unaibrrgn** [comment]
Dear @k-eight-v,

we'll have a look and let you know a solution as soon as possible. 

Regards,
Unai.

**Comment by k-eight-v** [comment]
Fixed, had to move logos to show them. But one problem is with rest uri: 
https://registrytest.sise.envir.ee/registry/rest?uri=http%3A%2F%2Fregistrytest.sise.envir.ee&lang=et&format=jsonc&status=
getting : 
{
  "error" : {
    "code" : 404,
    "description" : "Element not found",
    "description-code" : "not-found"
  }
}

**Comment by unaibrrgn** [comment]
Dear @k-eight-v,

Is this item accesible through the backend administration instance?

Also, have you tried to access the item through its UUID instead of the URI? Your request should look something like this : [https://registrytest.sise.envir.ee/registry/rest?uuid=8f81ea04e282e23fa14493fc696869aa&lang=et&format=jsonc&status=](https://registrytest.sise.envir.ee/registry/rest?uuid=8f81ea04e282e23fa14493fc696869aa&lang=et&format=jsonc&status=).

At last, can you try to access more items through this process? Preferably some lower hierarchy elements like register items or subitems.

Thank you in advance.
Regards,
Unai.

**Comment by k-eight-v** [comment]
https://registrytest.sise.envir.ee/registry/rest?uuid=8f81ea04e282e23fa14493fc696869aa&lang=et&format=jsonc&status= : 
{
  "error" : {
    "code" : 404,
    "description" : "Element not found",
    "description-code" : "not-found"
  }
}

**Comment by unaibrrgn** [comment]
Dear @k-eight-v,
could you send us the database dump you are currently using on your instance? We will try to replicate the problem you are having.

Thank you in advance.

Regards,
Unai.

**Comment by k-eight-v** [comment]
[backup_all.txt](https://github.com/ec-jrc/re3gistry/files/13636405/backup_all.txt)
Here is my pg_dumpall from database.

**Comment by k-eight-v** [comment]
https://registrytest.sise.envir.ee/registry/searchapi it is seems working: 

{
  "responseHeader":{
    "status":0,
    "QTime":1,
    "params":{}},
  "response":{"numFound":0,"start":0,"numFoundExact":true,"docs":[]
  }}
