### ISSUE TITLE
Re3gistry2 version 2.5.0 webapp problem

### ISSUE THREAD

**Issue by TeijoKal** [ec-jrc/re3gistry#324]
I installed Re3gistry2 version 2.5.0 and tried the application. Managed to install empty database version and the restapi is working. Now however has problem with webapp application.

I have the following configured in httpd:

DocumentRoot "/var/www/luettelopalvelu/public_html"
ServerName dev.luettelopalvelu.fi
 
ProxyPass /re3gistry2 http://localhost:8080/re3gistry2
ProxyPassReverse /re3gistry2 http://localhost:8080/re3gistry2
        
ProxyPass /registry/rest http://localhost:8080/re3gistry2restapi/items/any
ProxyPassReverse  /registry/rest http://localhost:8080/re3gistry2restapi/items/any

Then in webapp i tried to configure in conf.js:

// The app's base URLs
registryApp.domainURL = 'http://dev.luettelopalvelu.fi/registry';
registryApp.hostURL = 'http://dev.luettelopalvelu.fi/re3gistry2';
registryApp.searchURL = 'http://dev.luetteloplavelu.fi/registry/search';
registryApp.searchApiURL = 'http://dev.luettelopalvelu.fi/registry/searchapi';
registryApp.dataServiceURL = 'http://dev.luetteloplavelu.fi/registry/rest';

Is there still something i have missed to make the webapp work??

**Comment by jescriu** [comment]
Dear @TeijoKal,
I will bring this topic to the attention of our contractors, who probably missed it.

@campoxab and @arantzaetxebarria - My suggestion is to organise a technical meeting next week to unlock FI Re3gistry installation.
And please assure to respond, classify and start working in the issues in a maximum 3 business days.

**Comment by arantzaetxebarria** [comment]
Dear @TeijoKal, 

Apologies for the delayed response.
We will start the analysis of the problem. We will keep you updated on our findings and we will try to provide an answer as soon as possible.

Regards

**Comment by EnekoRuiz** [comment]
Dear @TeijoKal,

Thank you for bringing this issue up. We would like to ask you a couple of questions in order to understand the problem better. 
- Can you check if the items in the database are generated with the URI you have provided? (In this case dev.luettelopalvelu.fi/registry). 
- Can you attach a screenshot of what happens when you try to access the frontend of the application? Any error that shows up on console on the page load would be appreciated. 

Thank you for your feedback.

Regards, 
Eneko

**Comment by TeijoKal** [comment]
Here is the screen shot of the Admin start page (http://dev.luettelopalvelu.fi/re3gistry2).

<img width="854" alt="StartPage" src="https://github.com/ec-jrc/re3gistry/assets/114986037/ec487235-a8d3-4c5f-bf2e-ab66efabc9e3">



And the restapi is working as it should be.
For example 
https://dev.luettelopalvelu.fi/registry/rest?lang=fi&uri=http://dev.luettelopalvelu.fi/codelist/KiinteistonluovutuksenKohdistumisenLaji&format=xml

Returns the following:


<img width="755" alt="RestAPI" src="https://github.com/ec-jrc/re3gistry/assets/114986037/0b784bbc-6c62-484c-8ebd-cc23ed0c4ef1">




https://dev.luettelopalvelu.fi/registry results the following

<img width="884" alt="Registry" src="https://github.com/ec-jrc/re3gistry/assets/114986037/6ae2a004-1205-4f94-9425-09b6de43b37b">

**Comment by EnekoRuiz** [comment]
Dear @TeijoKal,

The URI seems to be fine, but we still need some more information about the issue. 
- Can you attach some screenshots showing the console errors when accessing the frontend?
- Can you try to access a children item on the frontend? (We want to check if the issue is with the main page only or if it is present on the whole frontend).

Regards, 
Eneko

**Comment by TeijoKal** [comment]
There is no error messages. Only it does not show the data.

Here is the screen shots of the example data entry.

<img width="854" alt="Malli_1" src="https://github.com/ec-jrc/re3gistry/assets/114986037/b135b710-5090-467e-a7fc-ce0bd845956e">


<img width="804" alt="Malli_2" src="https://github.com/ec-jrc/re3gistry/assets/114986037/12a8be1f-7669-4cad-8115-8570f91df375">

**Comment by TeijoKal** [comment]
Here is the installation process that i made.

[Installing_re3gistry_2.5.0.docx](https://github.com/ec-jrc/re3gistry/files/13499953/Installing_re3gistry_2.5.0.docx)

**Comment by unaibrrgn** [comment]
Dear @TeijoKal,
we will try and replicate the error that you're currently having in that installation process in order to solve it. For that, could you send us the database dump you used for the migration?

Thank you in advance,
Unai.

**Comment by unaibrrgn** [comment]
Dear @TeijoKal,

Analysing the docx file with the screenshots you provided, specifically in this screenshot you indicate that ''There is no visible data in this Finnish subpage''.

![image](https://github.com/ec-jrc/re3gistry/assets/75972112/5537d354-44f6-4133-90c5-fae386a0bb92)

What exactly is not visible? (we see the screenshot with data) Do you mean the table with the "available items"?
Could you send us a screenshot of the part where you see that the data is not loaded?
Best regards,
Unai.

**Comment by TeijoKal** [comment]
If after migration i open the Content the visible is the following:

The Finnish subpage:

![image](https://github.com/ec-jrc/re3gistry/assets/114986037/e6732c06-7e6c-4aa9-abdd-ec6fc03b2d7a)

And the English subpage

![image](https://github.com/ec-jrc/re3gistry/assets/114986037/c1e30f1f-dc7e-4b7f-b638-6a6529e9c835)

If i now choose Koodiluettelorekisteri in Finnish subpage the Available items stays empty

![image](https://github.com/ec-jrc/re3gistry/assets/114986037/0efca567-1bfb-451f-9fe5-a74e73da10da)

But if i choose the English subpage the Available items are all visible

![image](https://github.com/ec-jrc/re3gistry/assets/114986037/6f5bbbbb-004f-4f50-a5e3-b1425bc1093a)

**Comment by iratigarzon** [comment]
Dear @TeijoKal,

Since this issue pertains to an older version of the app, we recommend installing the latest version. If you continue to experience this issue, please open a new ticket.

Best regards,

Irati
