### ISSUE TITLE
Reusable JSON-LD context(s)

### ISSUE THREAD

**Issue by arantzaetxebarria** [ec-jrc/re3gistry#327]
This issue comes from INSPIRE Registry helpdesk https://github.com/INSPIRE-MIF/helpdesk-registry/issues/64
From: [saxomoose](https://github.com/saxomoose)

> I am looking for reusable JSON-LD context(s) of the INSPIRE vocabularies. I see that the INSPIRE registry does expose some data in RDF/XML. Maybe someone somewhere made the effort of creating JSON-LD context(s)?

> I found this workspace / org: https://github.com/inspire-eu-rdf.
> It is technically possible to draw the necessary linked data artefacts from these ontologies (JSON-LD contexts,...).
> However, the last commit on [inspire-rdf-vocabularies](https://github.com/inspire-eu-rdf/inspire-rdf-vocabularies) dates back to 6 years ago. Is there any plan to revive this initiative?

**Comment by jescriu** [comment]
After having analysed this enhancement the JRC INSPIRE team has decided to postpone its potential implementation waiting for the upcoming discussion on the future of the Re3gistry open-source software.
For the above-mentioned reason, this item is temporarily closed.
