### ISSUE TITLE
The first level of the  register does not work

### ISSUE THREAD

**Issue by idevisser** [ec-jrc/re3gistry#328]
I think we have the same problem as issue #322. 
The first level of the register does not work, accessible via https://test.inspireregister.nl. We have the impression that the addition registry should be left out of the basic URL that is included in the register. Is that right? or is there a parameter somewhere else that can be adjusted so that the main level works.
The lower levels do work, see https://test.inspireregister.nl/codelijst

![image](https://github.com/ec-jrc/re3gistry/assets/10847083/1d1b1e8e-3c47-4258-9a4f-4faff864d19a)

**Comment by unaibrrgn** [comment]
Dear @idevisser,
sorry to hear that. We will take a look and give you feedback as soon as possible, but first I wanted to ask a question. While creating the register you are trying to access did you check this option? 
![11231](https://github.com/ec-jrc/re3gistry/assets/75972112/82e121b5-41a7-4e50-8a8d-dba31ad9899d)

Thank you for your feedback.
Regards,
Unai.

**Comment by rkaesehagen** [comment]
Hi @arantzaetxebarria. Where can we check whether the registry word is in the URI path? This instance was created in 2020 and @idevisser and I were not involved back then. Is there a place where we can see this? For your convenience I added some screenshots from the admin panel. Maybe these answer your question.

![67FA6FB5-E3FD-4F8E-8171-EB637DFC915C](https://github.com/ec-jrc/re3gistry/assets/127403111/bdca8e04-aa6a-464f-bb05-537678ea7de0)
![81535C43-AB59-421C-BA86-056609FA2256](https://github.com/ec-jrc/re3gistry/assets/127403111/db38899a-2a75-4233-9ae6-0b583d078ae9)

![CF811FF6-7963-4336-9D54-7A0FF1FF91EC](https://github.com/ec-jrc/re3gistry/assets/127403111/d7bec491-28e1-4c38-87f5-f43b7b8fe245)

**Comment by unaibrrgn** [comment]
Dear @rkaesehagen,
have you updated your instance since 2020? Have you ever been able to acess this first level? We think it might have to do something with bad cache. Try to delete the cache through the backend instance and try to access. If it is still not available try to do a full cache trough the same menu.

Regards, Unai.


![image](https://github.com/ec-jrc/re3gistry/assets/75972112/3ca50469-6cef-443c-8f76-44d52e82bbde)

**Comment by rkaesehagen** [comment]
Hi @unaibrrgn, The instance was first created in 2020 (inspireregister.nl). In that instance the root category /registry is not showing. /codelijst is working fine. Last month I did a fresh install of the re3gistry2 software at test.inspireregister.nl on a new server. I exported the old database and imported the database in the new environment.

The issue @idevisser reports happens in the old and the new environment, so we hope that it is something in the database or a setting that is causing this behaviour. 

Rob

**Comment by unaibrrgn** [comment]
Dear @rkaesehagen,
Please try and delete the cache as I indicated previously and then try to access the first layer that is currently unavailable. If that doesn't work do a brand new cache of the instance and once it ends try to access the first layer. We really think this might have to do something with cache.

Keep us updated on the results and we'll look onto them as soon as possible.

Regards,
Unai.

**Comment by rkaesehagen** [comment]
Hi @unaibrrgn , we did a rebuild of the cache of test and production. Nothing changed in the behaviour of https://test.inspireregister.nl/registry.

**Comment by unaibrrgn** [comment]
Dear @rkaesehagen, 
could you send me the database dump of the test instance? Could you also send me the cache related files so we can discard a cache issue? 

We'll try to find out where the problem might come from.

Regards,
Unai.

**Comment by rkaesehagen** [comment]
Hi @unaibrrgn, attached the export of the database. Which are the cache related files you mention? Can you be more specific?

[2311re3gistry2.sql.zip](https://github.com/ec-jrc/re3gistry/files/13300411/2311re3gistry2.sql.zip)

**Comment by unaibrrgn** [comment]
Dear @rkaesehagen, 
thank you, we'll take a look to see if there's any problem with the database. For now i don't think we need the cache files so don't worry about it. We'll let you know if we need the cache data.

Regards,
Unai.

**Comment by unaibrrgn** [comment]
Dear @rkaesehagen,
we actually could use the cache files to determine if there's something wrong with them. So if you could send us the whole 'ehcache' folder that would be perfect. 

This folder can be found inside the Tomcat's 'work' folder.

Thank you in advance,
Unai.

**Comment by rkaesehagen** [comment]
Hi @unaibrrgn, thanks for your support.
The ehcache plugin is not mentioned as prerequisite for re3gistry2. So it is not installed. Should i install it?

Rob

**Comment by unaibrrgn** [comment]
Dear @rkaesehagen,
Don't worry, ehcache is already implemented in the Re3gistry2. These files i mentioned earlier are in the Tomcat server's directories. Here's the complete route and a screenshot of how it might look like.

/usr/local/tomcat/work/ehcache

![image](https://github.com/ec-jrc/re3gistry/assets/75972112/4c541521-9442-4eb7-8910-859fb634402d)


We would need the ehcache directory found in that screenshot.

Thank you in advance,
Unai.

**Comment by rkaesehagen** [comment]
Hi @unaibrrgn,
We have no ehcache directory,
Our work directory is located in /var/lib/tomcat9/work (ubuntu server). It only contains a folder Catalina.

**Comment by unaibrrgn** [comment]
Dear @rkaesehagen,
Sorry for the confusion. We will try and replicate your problem in our local environment in order to discover a solution.
We'll keep you updated with any advancements we make.

Regards,
Unai.

**Comment by unaibrrgn** [comment]
Dear @rkaesehagen,
we managed to replicate and solve your problem in our local instance. The issue lies on the registry item on the database. This item is marked as reg_status = 5 . (which means it's a draft) We think this change must've been done by changing the values manually in the database collumn, as the registry level is not meant to have any status other than valid. (reg_status = 1)

To solve this you should go to the reg_item table of the database, search for the 'registry' item and change its reg_status from '5' (draft) to '1' (valid).

![image](https://github.com/ec-jrc/re3gistry/assets/75972112/201a2398-5cfd-4613-8c26-a556e4b3c72a)


Once the changes are made, the first level should be accessible through https://test.inspireregister.nl/registry .

Let us know if you have any doubts or problems while implementing the solution.

Regards,
Unai.

**Comment by unaibrrgn** [comment]
Dear @rkaesehagen,
were you able to implement the solution? Did you encounter any more problems?

Regards,
Unai.

**Comment by rkaesehagen** [comment]
HI @unaibrrgn, sorry for the delay. Your solution works. 
Tnx for your support.

**Comment by arantzaetxebarria** [comment]
Dear @rkaesehagen 

We are happy that your problem is solved. We proceed to close the issue, any other problem, please do not hesitate to contact us again.
