### ISSUE TITLE
Exception when finishing the install wizard

### ISSUE THREAD

**Issue by wdantuma** [ec-jrc/re3gistry#331]
Hello,

I was running a version 2.4.2  instance of re3gistry which was working. After installation the PostgresSQL database which it was running on was upgraded to version 14.7, re3gistry was still running fine.

Now i tried tot install a re3gistry version 2.5.0 next to the running 2.4.2 version but i'am getting the following exception when finishing the install wizard ( clicking the install button ):

```[EL Info]: connection: 2023-11-27 18:49:33.487--ServerSession(1010521056)--/file:/opt/tomcat/webapps/re3gistry2/WEB-INF/classes/_Re3gistry2 login successful
[EL Warning]: 2023-11-27 18:50:41.258--UnitOfWork(954442767)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.5.v20191016-ea124dd158): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_reg_item"
  Detail: Key (uuid)=(27f3dbdc7dbc69e5c2b3aa3ef79dc491) already exists.
Error Code: 0
Call: INSERT INTO reg_item (uuid, currentversion, editdate, external, insertdate, localid, ror_export, reg_action, reg_itemclass, reg_status, reg_user) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [11 parameters bound]
Query: InsertObjectQuery(eu.europa.ec.re3gistry2.model.RegItem[ uuid=27f3dbdc7dbc69e5c2b3aa3ef79dc491 ])
```

The table reg_item in the database is empty ( fresh database )

**Comment by unaibrrgn** [comment]
Dear @wdantuma,
thanks for reporting the issue. Each instance of the re3gistry software has to have its own independent database, so you should have 2 instances and 2 databases. From the error looks like the second instance is pointing to the same database as the first one.

You should be able to install it correctly with an independent and clean database.
Let us know if you find any problems or have any doubts on this topic.

Regards, 
Unai.

**Comment by wdantuma** [comment]
I recreated the DB and tried again today. Seems to work now
