### ISSUE TITLE
Re3gistry version 2.5.0 webapp problems

### ISSUE THREAD

**Issue by TeijoKal** [ec-jrc/re3gistry#336]
I tried to install the webapplication. Now the problem is that it is not working. The respApi is working properly, you can inquery the data with success.

In conf.js there is the following lines

// The app's base URLs
registryApp.domainURL = 'http://dev.luettelopalvelu.fi/registry';
registryApp.hostURL = 'http://dev.luettelopalvelu.fi/re3gistry2';
registryApp.searchURL = 'http://dev.luettelopalvelu.fi/registry/search';
registryApp.searchApiURL = 'http://dev.luettelopalvelu.fi/registry/searchapi';
registryApp.dataServiceURL = 'http://dev.luettelopalvelu.fi/registry/rest';

How can i check that the lines i configured are working?? What should be the response of each url?? How to check that the response coming from each url is as it should be.

**Comment by unaibrrgn** [comment]
Dear @TeijoKal,

These are the expected results of the different URLs:

- **registryApp.domainURL** = Should return the frontend home page. As we've seen on the #324 this URL is working as it leads you to the front page.
- **registryApp.hostURL** = Should return the backend home page. As we've seen on the #324 this URL is also working correctly.
- **registryApp.searchURL** = Should return a frontend page of a failed frontend data search. It should look like this: 

![image](https://github.com/ec-jrc/re3gistry/assets/75972112/7cc8c318-1e12-4b48-915f-ebd4b77b3dd4)

- **registryApp.searchApiURL** = Should return a 400 type response from the API. Should look something like this: 

![image](https://github.com/ec-jrc/re3gistry/assets/75972112/32c893e0-cd19-400f-b7b4-74762e2b9d02)

-**registryApp.dataServiceURL** = Should return a 400 type response from the API lacking parameters. Should look something like this: 

![image](https://github.com/ec-jrc/re3gistry/assets/75972112/349de072-866a-4caa-a781-16a71f753947)


Regards,
Unai.

**Comment by TeijoKal** [comment]
Ok, thanks.

I was checking our environment and the problem seems to be Solr. Is there any instructions and ideas how to configure Solr?
