### ISSUE TITLE
Remove registers and items

### ISSUE THREAD

**Issue by danicgc** [ec-jrc/re3gistry#34]
Dear team,
I would like to remove some specific registers and items created (not classes but contents). How can I do it? 
Thank you,
P.S. I'm working with Re3gistry 2.0

**Comment by emanuelaepure10** [comment]
Dear @danicgc,

Following the ISO 19135 standard, once an item is added to the system (passing from "proposed" status to "valid") it can never be deleted via interface.

What you can do is:
1. if is still in "proposed" status that you can just redraw the action containing the item
2. if the item has "valid" status the item can be "supperseded", "invalidated" ore "retired"
3. or just delete them from the database. 

Please remember that the registry was created to contain persistent items.

**Comment by danicgc** [comment]
OK. Thank you very much.
