### ISSUE TITLE
CSS issue on form field errors

### ISSUE THREAD

**Issue by ZakarFin** [ec-jrc/re3gistry#344]
The placement that's used here:
https://github.com/ec-jrc/re3gistry/blob/v2.5.1/sources/Re3gistry2/src/main/webapp/res/css/re3gistry2.css#L422-L424

Doesn't really work on the login form:
![image](https://github.com/ec-jrc/re3gistry/assets/2210335/432b0a8c-b4c5-4d74-ba7a-7d7c837a09ad)

Maybe it's designed to work when there is a label on the field?

**Comment by unaibrrgn** [comment]
Dear @ZakarFin,
thank you for pointing the problem, we will take a look at it as soon as possible.

Regards,
Unai.

**Comment by unaibrrgn** [comment]
Dear @ZakarFin,
the issue has been solved and will be implemented in the following release. Thanks again for pointing it out.

Regards,
Unai.

**Comment by iratigarzon** [comment]
Dear @ZakarFin,

I wanted to inform you that in the latest release ,[ 2.5.3](https://github.com/ec-jrc/re3gistry/releases/tag/v2.5.3), this issue has been resolved.

Regards,
Irati.
