### ISSUE TITLE
Version 2.5.0 Cache problem

### ISSUE THREAD

**Issue by TeijoKal** [ec-jrc/re3gistry#346]
I installed version 2.5.0 and manually insert some data. Now if i go to Admin interface and there to Registry manager dashboard and there choose Data export. Now if i choose  Cache all - Master language the operation is stucked. It has shown the same message now more than a day.

It seems that the problem might be Solr. I had core there named Re3gistry2 and not re3gistry2.

<img width="769" alt="Cache_stucked" src="https://github.com/ec-jrc/re3gistry/assets/114986037/c9ad1338-cad5-4e0a-aa4e-634ca5f51b21">

**Comment by TeijoKal** [comment]
Managed to stop that cache stuck by removing the tag
cacheall_complete.running
in the directory re3gistry2/WEB-INF/classes/configurations_files

**Comment by unaibrrgn** [comment]
Dear @TeijoKal,
depending of the size of the database the cache will last quite a lot of time so this might be its regular working pace. We don't quite understand the Solr issue you are talking about, could you give more details on the matter?

Regards,
Unai.

**Comment by TeijoKal** [comment]
It seems that Solr is not working for Re3gistry. Need instructions how Solr should be set up for Re3gistry ??

**Comment by TeijoKal** [comment]
Managed to made Solr work properly. And now indexing is working.
