### ISSUE TITLE
The label field becomes empty when quotes are entered.

### ISSUE THREAD

**Issue by arantzaetxebarria** [ec-jrc/re3gistry#349]
When creating or modifying an item and inserting quotes in the **Label** field
![image](https://github.com/ec-jrc/re3gistry/assets/64014694/4cdb0a64-a95d-4bc8-aa59-d8d24877a001)

The **Label** field is empty

![image](https://github.com/ec-jrc/re3gistry/assets/64014694/fdc72f34-7f59-4f0d-80c7-b561d4d223cb)

In the edition case, the proposal appears empty also

![image](https://github.com/ec-jrc/re3gistry/assets/64014694/b91cde39-fd22-4071-ac44-ec92739ca48a)

**Comment by iratigarzon** [comment]
This issue has been reviewed and fixed. It will be available in the upcoming release, version 2.5.3.
