### ISSUE TITLE
Can't find associated items

### ISSUE THREAD

**Issue by danicgc** [ec-jrc/re3gistry#35]
Dear team,
I have tried to remove a register class but the application says that it has some items associated although I can't find them (nor in the content section nor in the structure section). It had an item (draft) but I removed its corresponding class.
Is there any way to force the deletion or maybe reset the database...?
Thank you
P.S. I'm working with Re3gistry 2.0

**Comment by emanuelaepure10** [comment]
Hi @danicgc ,

Once you create a register, this has an associated itemclass. 
And following the ISO 19135 standard, once an item is added to the system (passing from "proposed" status to "valid") it can never be deleted via interface.
That means that the register item it can never be deleted, and so to itemclass associated.

You can remove just one itemclass created and without any associated item.

Best regards,
Emanuela

**Comment by danicgc** [comment]
OK. Thank you
