### ISSUE TITLE
Cache - Feasibility study to improve caching performance 

### ISSUE THREAD

**Issue by arantzaetxebarria** [ec-jrc/re3gistry#358]
Improve database retrieval by retrieving item information more efficiently.
Select those items that have been modified or that are not cached (new button?)

**Comment by iratigarzon** [comment]
Performance has been improved by optimizing database retrieval. Now, only items that have been modified will be selected. This enhancement will be available in version [2.6.0](https://github.com/ec-jrc/re3gistry/releases/tag/v2.6.0).

**Comment by iratigarzon** [comment]
Performance has been improved by optimizing database retrieval. Now, only items that have been modified will be selected. This enhancement will be available in version [2.6.0](https://github.com/ec-jrc/re3gistry/releases/tag/v2.6.0).
