### ISSUE TITLE
Publish changes on registry element

### ISSUE THREAD

**Issue by danicgc** [ec-jrc/re3gistry#36]
Dear team,
I have modified some contents of the registry element but, although it has been publish by the Registry Manager, it remains as Draft. How can I make it Valid?
Thank you,
P.S. I'm working with Re3gistry 2.0

**Comment by emanuelaepure10** [comment]
Dear @danicgc,

Please go in the tab "Submitting Organisations" (hoping that you have this role) and click th button "Submit to Control Body" related to your action. 
Than if you or a colleague has the "Control Body" role can "Aprove", "Aprove with Changes" or just "Reject" the action with the modification of the content you have done.
The last step is of the "Registry Manager" to "Publish" the change and once all this is done your modification will apear on the public interface of you system.

In this moment the item has passed fron status "Draft" into status "Valid".

Best regards,

**Comment by danicgc** [comment]
Dear @emanuelaepure10,
The problem is only with the "registry" element, i.e. the top/root element. Despite publishing it (after submit, approve, etc.), it does not change to Valid.

**Comment by emanuelaepure10** [comment]
Dear @danicgc,

On the registry item once you have done a modification you should get a screen like that
![image](https://user-images.githubusercontent.com/67077116/111445852-1533b680-870c-11eb-85fb-6ca69997efb3.png)

and than, as it is an action that can be done just by the "Registry Manager" you should see in the related tab something like
![image](https://user-images.githubusercontent.com/67077116/111446031-41e7ce00-870c-11eb-9b78-4df3407e6ecb.png)


The action is in "Draft". And is going to change the status once the action has been published.
![image](https://user-images.githubusercontent.com/67077116/111446426-aefb6380-870c-11eb-996c-08e73c9b83de.png)


Please let us know if this is solving your issue.
Best regards

**Comment by danicgc** [comment]
Dear @emanuelaepure10,
The problem is, in fact, that the status does not change after doing that.

**Comment by emanuelaepure10** [comment]
@danicgc 

I cannot reproduce you issue.

I have looked into the reg_itemproposed table after editing the registry item and the action is in "Draft", but after publishing the action the reg_itemproposed doesnt have anymore the registry item into the table. 
As well the table reg_aciton has the new entry in status "Draft", but after publishing the status of tha action change into "Published".

Can you please provide more details on what do you mean or the steps you are doing?

Thank you in advanced

**Comment by danicgc** [comment]
Hi @emanuelaepure10,
The steps are the ones you explained very well and the status of the action is also "Published". The problem is that the reg_status field of the reg_item table does not change its value from 5 (Draft) to 1 (Valid). It only happens with the registry element ("the top level" one).
As a workaround, I change the value directly in the table but, if I am not wrong, it is supposed to be changed within the publishing workflow of this item...

**Comment by emanuelaepure10** [comment]
@danicgc 
You dont need to change the value in the table. The status of the proposed item is changing automaticaly during the workflow.

Passing from status 5 - "Draft" (When is still with the Submitting Organisation) to  status 6 - "Submited" when to submitting organisation has submitted the item. From here  depending on the action of the Control Body the status can change into 12 - "Accepted", the item can be resubmitted to the Submitting Organisation for review or deleted/rejected. If the item is published the action change the status to 14 "Published" and the item goes from itemproposed to item.
  
 The reg_action is changing status hand by hand with reg_itemproposed.
 In all this workflow of making a CLARIFICATION the reg_item that you are changing is never changing status! 

Are you align with the latest modification of the code?

Thnak you in advanced

**Comment by danicgc** [comment]
Hi @emanuelaepure10,

About the version of the code, we deployed the one available in February 2021. Is there any newer?

Some clarifications:
- I have already published the registry, a code list and some codes successfully. The problem is when modifying something in the registry element (the first of the contents).
- The action status changes to "Published" (when publishing) successfully, but the **content status** remains "Draft" (does not change to "Valid").

The steps I follow:
**1.** I modify the content summary of the registry element and click "Save clarification":
![imatge](https://user-images.githubusercontent.com/60217335/112265272-862a1f80-8c72-11eb-98c2-07a316f0532f.png)

2. If it were another kind of item, I should approve the change in Submitting Organisations, Control Body and Register Manager (it appears the buttons...), but in the case of the registry element (only), there is only the option of clicking "Publish" in the Registry Manager tab (and then "Yes" when confirmation is requested):
![imatge](https://user-images.githubusercontent.com/60217335/112265831-6cd5a300-8c73-11eb-930b-33b027d92028.png)

The result is that the action status is then "Published"
![imatge](https://user-images.githubusercontent.com/60217335/112266851-e326d500-8c74-11eb-9d5c-462081be931a.png)

But the content status is still "Draft" (and then I have to change the reg_item table as workaround to make it "Valid"):
![imatge](https://user-images.githubusercontent.com/60217335/112266953-06518480-8c75-11eb-8653-73de00f32c6a.png)

Hope it helps to reproduce the problem. Maybe there was a misunderstanding in previous messages between "action status" and "content status".

**Comment by emanuelaepure10** [comment]
@danicgc 

Thank you very much for reporting it.
Indead, seems that a small typos has created a bug.

Before we publish a new version you could already solve the bug on your side
Go in the file
https://github.com/ec-jrc/re3gistry/blob/master/sources/Re3gistry2JavaAPI/src/main/java/eu/europa/ec/re3gistry2/javaapi/handler/RegActionHandler.java
and change 
at line 413 the key
KEY_ITEMCLASS_TYPE_REGISTER
to
KEY_ITEMCLASS_TYPE_REGISTRY

Thank you again
Emanuela

**Comment by df-git** [comment]
Solved in release [v2.1.0](https://github.com/ec-jrc/re3gistry/releases/tag/v2.1.0).
