### ISSUE TITLE
Version 2.5.0 Bulk import instruction needed

### ISSUE THREAD

**Issue by TeijoKal** [ec-jrc/re3gistry#368]
I have Re3gistry 2.5.0 installed and tried to use Bulk import. But the problem is that compared to version 1.3.1 the language is not the same. So en,fi or sv are not working. How should the language data should be marked in Bulk import csv file ??

There is need to some example csv file for Bulk import in the manual.

**Comment by TeijoKal** [comment]
Now have been trying for the swedish language values sv, swedish and 22
Nothing working

**Comment by TeijoKal** [comment]
Can you please give some idea what the language should be.

**Comment by unaibrrgn** [comment]
Dear @TeijoKal, in the Re3gistry2 2.5.0 version the bulk import/edit only works in the app's main language. The code solve for making bulk processes in different languages other than the main one was introduced in the 2.5.2 release. You can see an example of how the bulk import/edit CSV files are formed by downloading the template that is available in the bulk page.

![image](https://github.com/ec-jrc/re3gistry/assets/75972112/07bc725b-81b7-456b-96b0-66d70107cb40)

If you have any problems following the structure or making bulk processes with the main language dont hesitate to contact again.

Regards,
Unai.

**Comment by TeijoKal** [comment]
Ok. Should try to install 2.5.2 and try again. Thanks.
