### ISSUE TITLE
(Improvement) Wrong Registry Web page when Browser language is not an INSPIRE language

### ISSUE THREAD

**Issue by arantzaetxebarria** [ec-jrc/re3gistry#369]
This issue comes from the [INPIRE registry repository](https://github.com/INSPIRE-MIF/helpdesk-registry/issues/83), this ticket is created where development will take place to implement a solution.

> When accessing http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/noLimitations with a Browser that is not configured in an INSPIRE language (for instance, Catalan), the web page is wrong. It seems that is trying to recover the text in catalan and it does not exist:
![image](https://github.com/ec-jrc/re3gistry/assets/64014694/a9242fec-741e-4d40-a1cf-e226b57ccce2)

> Our metadata are implemented in a Geonetwork catalog, therefore, when pressing this link in the catalog it goes to that wrong Web page, making our catalog to have an incorrect behaviour.

![image](https://github.com/ec-jrc/re3gistry/assets/64014694/7ae56548-aa85-4f4f-9eae-37e5dc8d8631)

> This happens with all the metadata codelist. Examples:
> http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/noLimitations
> https://inspire.ec.europa.eu/metadata-codelist/OnLineDescriptionCode/accessPoint
> http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory
> http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoManagementService
> http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/humanGeographicViewer
> 
> As an improvement, if the description in the registry does not exists in the language of the browser, at least return it in english, instead of returning a Web error message.
> 
> Thanks and best regards
> 
> Montse
> 
>

**Comment by iratigarzon** [comment]
After analyzing the issue, we observed that the language selector detects if it's a language recognized by the European Union and sets it accordingly. However, the INSPIRE registry may not be available in that language. To address this, we have added a validation so that the language selector displays your browser's language if it is available in the system; otherwise, it defaults to the master language.
