### ISSUE TITLE
2.5.2 Bulk import failure

### ISSUE THREAD

**Issue by TeijoKal** [ec-jrc/re3gistry#370]
I installed the version 2.5.2 and tried the Bilk import feature. The main language is finnish and i tried to import swedish data. Did not work.

When trying to import the swedish data the result is the following:

<img width="775" alt="Näyttökuva 2024-03-08 103627" src="https://github.com/ec-jrc/re3gistry/assets/114986037/0fc332ca-c62d-414e-8c80-df485868ae43">

But the finnish data is there in the system already

<img width="803" alt="Näyttökuva 2024-03-08 103741" src="https://github.com/ec-jrc/re3gistry/assets/114986037/61bc2ac3-dc2f-493c-8487-6849e153fa96">

**Comment by unaibrrgn** [comment]
Dear @TeijoKal,
i'm sorry to hear that. Could you send me a little insight of the item structure you are using and the exact bulk import sentence you are inputting? At which level are you executing the bulk import process and which are the cointained items etc. Also, looks like the ZoneTypeCode item is also failing. Is the master language missing for this one or is it also failing?

Regards, 
Unai.

**Comment by TeijoKal** [comment]
Was trying the Bulk import in the first level of the hierarchy.


<img width="792" alt="Näyttökuva 2024-03-11 112922" src="https://github.com/ec-jrc/re3gistry/assets/114986037/4b9ccef1-d150-475e-8b21-8789efcb2671">


<img width="791" alt="Näyttökuva 2024-03-11 113100" src="https://github.com/ec-jrc/re3gistry/assets/114986037/215ee968-6012-49bf-b374-6c450ece2a52">


And the file was the following:

LocalID|Language|label|definition|collection
ErityislaeillaSuojellutRakennusperintokohteet|sv|Byggnadsarvsobjekt skyddade med speciallagstiftning|Byggnadsarvsobjekt skyddade med speciallagstiftning|
ZoneTypeCode|sv|Områdestypkod|Högnivåklassificering som definierar typ av område med särskild förvaltning/begränsningar/reglering.|

And the ZoneTypeCode was like the ErityislaeillaSuojellutRakennusperintokohteet. The entry is in finnish in the data but the error says different.

**Comment by TeijoKal** [comment]
Here is the dump of our database (taken with pg_dump)

[dumppi_20240312.txt](https://github.com/ec-jrc/re3gistry/files/14571587/dumppi_20240312.txt)

**Comment by unaibrrgn** [comment]
Dear @TeijoKal,
Reviewing the information that you have been providing us, we noticed that in the last screenshot, there is a button (Bulk Import) that in the v2.5.2 version is different. 

The bulk import/edit button has been changed to a generic button (Start bulk process) with a dropdown component for both import/edit that separates both processes and solves bugs in version 2.5.2.

Could you please check that you have installed the correct version? 
Thanks in advance.

Regards,
Unai.

**Comment by TeijoKal** [comment]
I just installed the Re3gistry again to make sure (version 2.5.2). Installed re3gistry2 and re3gistry2restapi found in the distribution package (/dist directory).

And tried again the Bulk import with the exact same results.

Is there a wrong version published in the v2.5.2 package??

**Comment by unaibrrgn** [comment]
Dear @TeijoKal,
Currently the dist package is out of date. The updated code is located in the sources folder. We are aware of this and will solve this in a forthcoming release.

Sorry for the confusion.

Regards,
Unai.
