### ISSUE TITLE
2.5.2 Bulk import not working

### ISSUE THREAD

**Issue by TeijoKal** [ec-jrc/re3gistry#386]
I build myself the version 2.5.2 from Re2gistry package. So this time the Bulk import should have been fixed.

Tried to import some data to the application. No success.

I used the following file to import the data

[koe_fi.csv](https://github.com/ec-jrc/re3gistry/files/14651492/koe_fi.csv)

I chose to import with Bulk import

<img width="815" alt="Bulk_import" src="https://github.com/ec-jrc/re3gistry/assets/114986037/3b682677-caa2-4a02-90a4-42138acfd1b0">

And chose the file to import. The result was success (at least what it said).

<img width="764" alt="Success" src="https://github.com/ec-jrc/re3gistry/assets/114986037/f19df644-c717-4e6c-9193-74ae7746a1c1">

And even the mail come that said that it was success.

<img width="331" alt="Mail" src="https://github.com/ec-jrc/re3gistry/assets/114986037/d252d592-f8db-4caf-a9ff-18b87c2dd45d">

Went back to Management interface and published the import result.

And after that nothing new came to the list of items.

**Comment by unaibrrgn** [comment]
Dear @TeijoKal,
we recently tried on our local instance with the database you've previously provided us with in another issue and we don't seem to have those problems even with the csv you've now provided us with. The import works correctly, the actions are displayed and the new items appear on the list of items along with the rest.

When you say "And after that nothing new came to the list of items.", did the items disappear when publishing them from draft to valid? Are they still on a draft status? Are they not visible on the available items list pages on the content page?

Any more information that could help us replicate the problem would be appreciated.

Regards,
Unai.

**Comment by TeijoKal** [comment]
Yes the new items did not show after published them from draft to valid. When i checked the list of the published items there was only 7 items in the list to publish.

Can you send me a working war file of Re3gistry2. It seems that even the building with Netbeans worked in my environment seems that the result war file is not working properly :(

**Comment by unaibrrgn** [comment]
Dear @TeijoKal, 
we took a deeper look and those 7 items that are getting published should not be in the .csv, as they are being edited and not imported. We removed those 7 entries from the file and did a succesful import. You have to isolate the 2 processes.

If you want to add the changes to those 7 entries you have to put them in a csv file and make a bulk edit.

![image](https://github.com/ec-jrc/re3gistry/assets/75972112/2ba152fc-eaff-47a3-8e6c-f6e77ab27524)

Regards,
Unai.

**Comment by TeijoKal** [comment]
Ok. I removed the 7 lines from the file and now it worked. Thanks!
