### ISSUE TITLE
On administration side, a database error is displayed and the "Available items" table is not displayed

### ISSUE THREAD

**Issue by arantzaetxebarria** [ec-jrc/re3gistry#396]
On the administration side, a database error is displayed and the "Available items" table is not displayed

![image](https://github.com/ec-jrc/re3gistry/assets/64014694/e15e6b2e-7d20-4ccb-a22b-eaece7e23a18)
![image](https://github.com/ec-jrc/re3gistry/assets/64014694/39ea40a7-b21f-4c6d-b5c7-e56b0c089cf1)

**Comment by iratigarzon** [comment]
Fixed an issue where a database error was displayed when viewing the "Available Item" table. This enhancement will be available in version [2.6.0](https://github.com/ec-jrc/re3gistry/releases/tag/v2.6.0).
