### ISSUE TITLE
Bulk Edit - It is not possible to update an empty RelationReference type field

### ISSUE THREAD

**Issue by arantzaetxebarria** [ec-jrc/re3gistry#397]
This error happens when updating the information on an EMPTY  RelationReference type field.
No error is displayed and the field just remains empty without updating the edited value.

**Comment by iratigarzon** [comment]
Fixed a bug that prevented modifications of a relationReference field when it was empty. This enhancement will be available in [version 2.6.0](https://github.com/ec-jrc/re3gistry/releases/tag/v2.6.0).
