### ISSUE TITLE
Investigate why sometimes empty fields are displayed in the front end.

### ISSUE THREAD

**Issue by arantzaetxebarria** [ec-jrc/re3gistry#399]
In this case, the empty fields are not displayed
https://inspire.ec.europa.eu/codelist/AccessRestrictionValue/forbiddenLegally
![image](https://github.com/ec-jrc/re3gistry/assets/64014694/b13ad7d2-177f-4e18-b77b-b58d1354fdf8)

However, in this other case, the empty fields are the same
https://inspire.ec.europa.eu/codelist/CEMTClassValue/IV
![image](https://github.com/ec-jrc/re3gistry/assets/64014694/ef48252d-e4bd-4744-9a6b-bf976c1e36d5)

In principle, the two items belong to the same class.

**Comment by iratigarzon** [comment]
Added validation to prevent empty fields from being displayed on the frontend. This enhancement will be available in [version 2.6.0](https://github.com/ec-jrc/re3gistry/releases/tag/v2.6.0).
