### ISSUE TITLE
Error when adding multiple items

### ISSUE THREAD

**Issue by matejsot** [ec-jrc/re3gistry#4]
I added 2 items to a register. Then I submited and published them. The first item is now visible in register, the second is not. It has "Accepted" status and is listed on the "New items proposed" list. I cannot do anything with this item now - I cannot edit it (since it has "Accepted" status) and I cannot publish it.

**Comment by df-git** [comment]
Dear @matejsot,
Thank you for your feedback. We updated the sandbox instance with the fix. Can you please check that the behavior is now correct?

**Comment by matejsot** [comment]
Now the behaviour is correct. Thanks.
