### ISSUE TITLE
Webapp javascript error after update 2.1

### ISSUE THREAD

**Issue by geoase** [ec-jrc/re3gistry#41]
Hi there,
first of all. Thanks for the recent update.

Unfortunately, after installing registry 2.1 a js error occurs in the webapp:

Uncaught TypeError: Cannot read property 'sort' of undefined app_core.js:240
    at renderProperties (app_core.js:240)
    at renderData (app_core.js:116)
    at Object.<anonymous> (app_core.js:84)
    at c (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at l (jquery.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2)

The url of the sandbox registry is https://inspire.geoase.eu/registry

Although, I pulled the latest master branch the java admin interface still shows me Version: 2.0.0

I do not know if this is only a problem with the webapp or if the response from 
https://inspire.geoase.eu/registry/rest?uri=https%3A%2F%2Finspire.geoase.eu%2Fregistry&lang=en&format=json
is not correct.

I use chromium Version 89.0.4389.90

Would appreciate your help. Thanks
G

**Comment by emanuelaepure10** [comment]
Dear @geoase ,

Please check out last update. That should solve your problem. 

Thank you
Have a great day

**Comment by geoase** [comment]
Hi Emanuela,
looks good. Thank you for the fast fix.
Best
G
