### ISSUE TITLE
Path ../re3gistry2/install does not work

### ISSUE THREAD

**Issue by antamasal** [ec-jrc/re3gistry#420]
Hello

I am having problems with the installation wizard.
I have mounted a solr version 8.11.3 and installed apache-tomcat-9.0.88
I have created two folders, one cache and another RSS and I have downloaded the funete code from github.
In the dist folder, I have set the [init.properties](https://init.properties/) with the following values:

dbhost=localhost
dbport=5432
dbname=re3gistry2
dbuser=postgres
dbpassword=password-
statusbaseuri=localhost:8080/r3egistry2
solrurl=http://localhost:8983/solr/
smtphost=smtp.test-url.eu
applicationrooturl=http://localhost:8080/r3egistry2
rsspath=/opt/instalacionre3gistry2/file
diskcachepath=/opt/instalacionre3gistry2/cache

and I have run ./init-config.sh

Afterwards, I created the re3gistry2 database and ran the database load script from dist/db-scripts/registry2_drop-and-create-and-init.sql and verified the creation of the database.

Finally, I copy the content of dist/app (re3gistry2 and re3gistry2restapi) into tomcat webapps and start the server.

The server starts up fine without errors but when I access http://localhost:8080/re3gistry2/install it redirects me to http://localhost:8080/re3gistry2/login and I can't access.

Is it properly installed? Am I missing something? How can I access to it?

Thank you

**Comment by iratigarzon** [comment]
Dear @antamasal,

The installation seems to be okay. Could you please check if there is a file called **system.installed** inside the **dist/app/re3gistry2/WEB-INF/classes/configuration_files** directory? If this file exists, please delete it. After doing so, the http://localhost:8080/re3gistry2/install path should work.

If the problem persists, please don't hesitate to contact us.

Best regards,

Irati.

**Comment by antamasal** [comment]
Hi,
It has worked!
That file was in the indicated path and by deleting it I was able to access the wizard.
Thank you

**Comment by iratigarzon** [comment]
This issue was re-open to reference the commit for the branch created to delete the file.
