### ISSUE TITLE
Error installing software by choosing the migration option

### ISSUE THREAD

**Issue by antamasal** [ec-jrc/re3gistry#427]
When I install the software by choosing the migration option, when I configure the database and click start, the process returns me to the first step of the wizard.
In the log, I only see that it has successfully logged into the database.
The version I am migrating is: Re3gistry 1.3.1
How could I finish the installation using the migration option?
Thank you

**Comment by iratigarzon** [comment]
Dear @antamasal,

Do you want to migrate from version 1.3.1 to the current version (2.5.3)?

Best regards,
Irati.

**Comment by antamasal** [comment]
Yes, exactly
Thanks!

**Comment by antamasal** [comment]
I have done it again from the beginning.
When the wizard starts, I put the migration option and username and password.
When I write the data, in the log I can see that it says that you have been able to log in and when I click install, it redirects me to the first step.
I attach the backup.

[backup_re3gistry6.zip](https://github.com/ec-jrc/re3gistry/files/15486176/backup_re3gistry6.zip)

_[EL Info]: 2024-05-29 16:43:12.416--ServerSession(1807173135)--EclipseLink, version: Eclipse Persistence Services - 2.7.5.v20191016-ea124dd158
[EL Info]: connection: 2024-05-29 16:43:12.543--ServerSession(1807173135)--/file:/opt/instalacionre3gistry6/apache-tomcat-9.0.88/webapps/re3gistry2/WEB-INF/lib/Re3gistry2Migration-1.0.jar_Re3gistry2Migration_url=jdbc:postgresql://localhost:5432/database=postgres login successful_


Thanks

**Comment by antamasal** [comment]
Any idea of ​​the error?
Best regards,

**Comment by iratigarzon** [comment]
Dear @antamasal,

We have tried running in our local instance, and it is working as expected. However, we have encountered an issue with passing your backup dump (.dmp) to a SQL file.

Could you please upload a SQL file? So we can check if an error is thrown related to the database when you click on the "Install" button.

Best regards, 

Irati.

**Comment by antamasal** [comment]
Hii!,
Here is the export in SQL format so you can review it better.
Looking at the export of the database, when I click the start button no error appears in the log but it has not finished installing.
Looking at the target database, I notice that many of the records have not been passed.
Thanks and greetings

[re3gistry.txt](https://github.com/user-attachments/files/15582578/re3gistry.txt)

**Comment by antamasal** [comment]
Any idea of ​​the error?
Best regards,

**Comment by iratigarzon** [comment]
Dear @antamasal,

We have reviewed the dump you provided and identified an issue with the migration process. It appears that the error occurs while trying to migrate the **CustomAttribute** table, which is causing the process to redirect you back to the first step. We are checking this issue and will inform you as soon as we have a solution.

Best regards,

Irati.

**Comment by antamasal** [comment]
Hi!!
Is there any news on this topic?
Thanks

**Comment by jescriu** [comment]
After having analysed this bug / enhancement the JRC INSPIRE team has decided to postpone its potential implementation waiting for the upcoming discussion on the future of the Re3gistry open-source software.
For the above-mentioned reason, this item is temporarily closed.

**Comment by antamasal** [comment]
Thank you very much for the information.
This issue blocks us from installing the Re3gistry software in our facilities.
Is there any time estimate for when this issue could be resolved?
Thank you and greetings.
