### ISSUE TITLE
Re3gistry 2.5.2 restapi error

### ISSUE THREAD

**Issue by TeijoKal** [ec-jrc/re3gistry#428]
Notice some not so good behaviour when using restapi.

In our 1.3.1 production environment:

https://www.luettelopalvelu.fi/codelist/KTJkiiKayttooikeusyksikkolaji/211/211.en.json
{
    "value": {
        "id": "http://www.luettelopalvelu.fi/codelist/KTJkiiKayttooikeusyksikkolaji/211",
        "thisversion": "http://www.luettelopalvelu.fi/codelist/KTJkiiKayttooikeusyksikkolaji/211:2",
        "latestversion": "http://www.luettelopalvelu.fi/codelist/KTJkiiKayttooikeusyksikkolaji/211",
        "historyversion": [
            {
                "version": "http://www.luettelopalvelu.fi/codelist/KTJkiiKayttooikeusyksikkolaji/211:1"
            }
        ],
        "language": "en",
        "label": {
            "lang": "fi",
            "text": "Kiinnike tai tuki voimajohtoa varten"
        },
        "description": {
            "lang": "fi",
            "text": "Lakannut 1999-12-31"
        },
        "itemclass": {
            "id": "CodeListValue",
            "label": {
                "lang": "en",
                "text": "Code list value"
            }
        },
        "status": {
            "id": " http://www.luettelopalvelu.fi/registry/status/retired",
            "label": {
                "lang": "en",
                "text": "Retired"
            }
        },
        "register": {
            "id": "http://www.luettelopalvelu.fi/codelist",
            "label": {
                "lang": "en",
                "text": "INSPIRE code list register"
            },
            "registry": {
                "id": "http://www.luettelopalvelu.fi/registry",
                "label": {
                    "lang": "en",
                    "text": "INSPIRE registry"
                }
            }
        },
        "codelist": {
            "id": "http://www.luettelopalvelu.fi/codelist/KTJkiiKayttooikeusyksikkolaji",
            "label": {
                "lang": "fi",
                "text": "KTJkii käyttöoikeusyksikkölaji"
            }
        }
    }
}

But then i tried the following in our demo (Re3gistry 2.5.2) environment:

https://dev.luettelopalvelu.fi/registry/rest?lang=en&uri=http://dev.luettelopalvelu.fi/codelist/KTJkiiKayttooikeusyksikkolaji/211&format=json

{
    "value": {
        "itemclass": {
            "label": {
                "text": "Codelist",
                "lang": "en"
            },
            "id": "Codelist"
        },
        "created": "2023-10-27 10:58 AM EEST",
        "language": "en",
        "definition": {
            "text": "<p>Keskussairaalat</p>",
            "lang": "fi"
        },
        "id": "http://dev.luettelopalvelu.fi/codelist/RakennuksenTarkkaKayttotarkoitus/211",
        "label": {
            "text": "Keskussairaalat",
            "lang": "fi"
        },
        "latestversion": "http://dev.luettelopalvelu.fi/codelist/RakennuksenTarkkaKayttotarkoitus/211",
        "thisversion": "http://dev.luettelopalvelu.fi/codelist/RakennuksenTarkkaKayttotarkoitus/211:1",
        "status": {
            "label": {
                "text": "Valid",
                "lang": "en"
            },
            "id": "statusbaseuri/status/valid"
        },
        "register": {
            "registry": {
                "label": {
                    "text": "Luettelopalvelu",
                    "lang": "fi"
                },
                "id": "http://dev.luettelopalvelu.fi/registry"
            },
            "label": {
                "text": "INSPIRE-koodiluettelorekisteri",
                "lang": "fi"
            },
            "id": "http://dev.luettelopalvelu.fi/codelist"
        }
    }
}

And it returned wrong data! I checked why this happened and it seems that because the data was not in our dev environment (KTJkiiKayttooikeusyksikkolaji and code value 211). After i added the entry of code value 211 it showed the correct result.

But the question is why it send some other answer that was not asked but the code value was the same 211??? And did not send any error message ??

https://dev.luettelopalvelu.fi/registry/rest?lang=en&uri=http://dev.luettelopalvelu.fi/codelist/KTJkiiKayttooikeusyksikkolaji/211&format=json

{
    "value": {
        "itemclass": {
            "label": {
                "text": "Codelist",
                "lang": "en"
            },
            "id": "Codelist"
        },
        "codelist": {
            "label": "",
            "id": ""
        },
        "created": "2024-05-30 05:59 AM EEST",
        "language": "en",
        "definition": {
            "text": "<p>Kiinnike tai tuki voimajohtoa varten</p>",
            "lang": "fi"
        },
        "id": "http://dev.luettelopalvelu.fi/codelist/KTJkiiKayttooikeusyksikkolaji/211",
        "label": {
            "text": "Kiinnike tai tuki voimajohtoa varten",
            "lang": "fi"
        },
        "latestversion": "http://dev.luettelopalvelu.fi/codelist/KTJkiiKayttooikeusyksikkolaji/211",
        "thisversion": "http://dev.luettelopalvelu.fi/codelist/KTJkiiKayttooikeusyksikkolaji/211:1",
        "status": {
            "label": {
                "text": "Valid",
                "lang": "en"
            },
            "id": "statusbaseuri/status/valid"
        },
        "register": {
            "registry": {
                "label": {
                    "text": "Luettelopalvelu",
                    "lang": "fi"
                },
                "id": "http://dev.luettelopalvelu.fi/registry"
            },
            "label": {
                "text": "INSPIRE-koodiluettelorekisteri",
                "lang": "fi"
            },
            "id": "http://dev.luettelopalvelu.fi/codelist"
        }
    }
}

**Comment by iratigarzon** [comment]
Dear @TeijoKal,

Thank you for bringing this to our attention. We will look into it.

Best regards,

Irati.

**Comment by TeijoKal** [comment]
Did you managed to reproduce the error? 
Do you have any estimate yet to the fix?
This error is only prohibiting to move this version 2 to our production environment.

**Comment by iratigarzon** [comment]
Dear @TeijoKal,

We have managed to find a solution, which will be available in version 2.6.1. However, could you please provide more information regarding the issue: "This error is only prohibiting us from moving this version 2 to our production environment." Specifically, when you enter all the information, it still prevents you from proceeding ?

Thank you.

Best regards,

Irati.

**Comment by TeijoKal** [comment]
I was discussing about this situation with our production people. And the result was that if it is not working reliable and giving wrong replies it is not acceptable to use in production environment.
