### ISSUE TITLE
Re3gistry 2.6.0 webapp logos missing

### ISSUE THREAD

**Issue by TeijoKal** [ec-jrc/re3gistry#446]
In the release package 2.6.0 there are lines in index.html

 <img class="mb-2" src="/registry/ecl-v2/static/logo/logo-1.png" alt="" width="50%" height="50%">

 <img class="mt-2" src="/registry/ecl-v2/static/logo/logo-2.png" alt="" width="30%" height="50%">

But in the release package in directory /ecl-v2/static/logo/ the pictures are missing with that names.

**Comment by TeijoKal** [comment]
Somohow the copied lines are not visible in issue ticket. So here again

src="/registry/ecl-v2/static/logo/logo-1.png" alt="" width="50%" height="50%"
src="/registry/ecl-v2/static/logo/logo-2.png

**Comment by iratigarzon** [comment]
Dear @TeijoKal,

Thank you for bringing this issue to our attention. It is true that the images are not in the established source location. We will add them to the specified directory. If you wish to add them to the correct location in your local instance, you can find the pictures at the following links:

dist/app/re3gistry2/res/img/logo-1.png
dist/app/re3gistry2/res/img/logo-2.png
Best regards,
Irati.

**Comment by TeijoKal** [comment]
Ok. Thanks.
