### ISSUE TITLE
Re3gistry 2.6.0 language issue in inserting data

### ISSUE THREAD

**Issue by TeijoKal** [ec-jrc/re3gistry#447]
I was adding data in the existing entries. There was already finnish entries in the system and and was adding swedish translations (added 21 entries). BUt i can not publish the swedish data!

In Manager view it is showing correctly the data but there is no action possible to the data.

<img width="793" alt="Manager_view" src="https://github.com/user-attachments/assets/21f7a29c-a017-4a2a-97c3-c4da5f416049">

And if you check the data and click the label to view:

<img width="775" alt="Manager_view_data" src="https://github.com/user-attachments/assets/ecedd5e6-f0ad-4fed-a67a-5ee02c70d0e3">

And in the Admin view it is giving an error message:

<img width="817" alt="Admin_view" src="https://github.com/user-attachments/assets/acd266a5-d17d-4fd7-b7a5-f5ee7e94fd4e">

And if you close the error message it is showin 21 empty lines.

<img width="805" alt="Admin_view_data" src="https://github.com/user-attachments/assets/dff7209b-dd3a-4a6c-942e-39e58d46f403">

**Comment by iratigarzon** [comment]
Dear @TeijoKal,

Have you followed the ISO 19135 workflow? Please check if it has been sent to the submitting organization, then to the control body, and finally accepted by the Register Manager or registry manager.

Best regards,

Irati

**Comment by TeijoKal** [comment]
Yes i have. And i am all the organizations, so i belong to all the groups.

**Comment by TeijoKal** [comment]
Ok. So you really need to go through all the steps. Not like if you add a new entry. Now it worked when went through all the steps.

**Comment by iratigarzon** [comment]
Dear @TeijoKal,

I investigated the issue related to the empty table and found a bug when trying to view a proposed list created in a language other than the master language. I have created a specific issue for this problem (#448), and it will be fixed in the upcoming version 2.6.1.

Best regards,

Irati.
