### ISSUE TITLE
Re3gistry 2.6.1 webapp error in redirect

### ISSUE THREAD

**Issue by TeijoKal** [ec-jrc/re3gistry#474]
Tried to use the webapp application. But it does not show the pictures. Console is giving the following errors:

<img width="394" alt="console_webapp" src="https://github.com/user-attachments/assets/69277442-4887-46af-9cbf-445b44a8d140">

So it seems that there is some redirect error in httpd?? But what ??

**Comment by Urkorue** [comment]
Dear @TeijoKal,

Can you provide us the complete route where this is calling? Maybe the direction has changed, or logos are missing here.

**Comment by TeijoKal** [comment]
The url:s used are the following
https://dev.luettelopalvelu.fi/registry/css/style_netrual.css
https://dev.luettelopalvelu.fi/registry/ecl-v2/static/logo/logo-1.png
https://dev.luettelopalvelu.fi/registry/ecl-v2/static/logo/logo-2.png

**Comment by TeijoKal** [comment]
Just checked and in index.html and search.html it is written
href="/registry/css/style_netrual.css"

But in the css directory there is file 
style_neutral.css

So there is a spelling mistake in your webapp application. But this is not resolving the pictures redirecting problem.

**Comment by TeijoKal** [comment]
And there is same spelling mistake also in api.html file

**Comment by TeijoKal** [comment]
So this is what i did to fix this
1. added to pictures to the correct directory (in this case /var/www/luettelopalvelu/public_html/ecl-v2/static/logo). Pictures logo-1.png and logo-2.png
2. Edited the webapp files  api.html, index.html and search.html. Changed the spelling mistake
    href="/registry/css/style_netrual.css" --> href="/registry/css/style_neutral.css"
3. Changed the configution of httpd. Added the following ecl-v2 line to the configuration
      ## Generic request to the registry
        RewriteCond %{REQUEST_URI} !^/re3gistry2
        RewriteCond %{REQUEST_URI} !^/registry/searchapi
        RewriteCond %{REQUEST_URI} !^/registry/search
        RewriteCond %{REQUEST_URI} !^/registry/rest
        RewriteCond %{REQUEST_URI} !^/registry/index\.html
        RewriteCond %{REQUEST_URI} !^/registry/js
        RewriteCond %{REQUEST_URI} !^/registry/css
        RewriteCond %{REQUEST_URI} !^/registry/img
        RewriteCond %{REQUEST_URI} !^/registry/conf
        RewriteCond %{REQUEST_URI} !^/registry/libs
        RewriteCond %{REQUEST_URI} !index\.html$
        RewriteCond %{REQUEST_URI} !\.json$
        RewriteCond %{REQUEST_URI} !^/registry/ecl-v2

        RewriteRule ^/(.*) /index.html [L]

And now it seems to be working.

**Comment by TeijoKal** [comment]
Only question is where it is where the link of these logo pictures are configured???

**Comment by arantzaetxebarria** [comment]
Hi @TeijoKal 

The pictures are here (you can see that were added 3 months ago) https://github.com/ec-jrc/re3gistry/tree/master/sources/Re3gistry2ServiceWebapp/public_html/ecl-v2/static/logo

And here is the configuration of the path:
https://github.com/ec-jrc/re3gistry/blob/a202095e7cf693e5591400b5c005bf7e653018eb/sources/Re3gistry2ServiceWebapp/public_html/conf/conf.js#L34

**Comment by TeijoKal** [comment]
But the question remaining is that where you will configure the link where it is going when clicking the picture??

**Comment by TeijoKal** [comment]
The url:s are also in api.html and search.html

**Comment by arantzaetxebarria** [comment]
Dear @TeijoKal 

Thanks for your input, I will close the ticket.

Regards
