### ISSUE TITLE
RSS release note xml file missing

### ISSUE THREAD

**Issue by AntoRot** [ec-jrc/re3gistry#48]
Concerning the latest version 2.2.0, no "release-note.xml" file is available in the folder [`dist/app/re3gistry2/WEB-INF/classes`](https://github.com/ec-jrc/re3gistry/tree/master/dist/app/re3gistry2/WEB-INF/classes) as indicated in the [administrator manual](https://github.com/ec-jrc/re3gistry/blob/master/documentation/administrator-manual.md#rss-release-note).

**Comment by df-git** [comment]
Dear @AntoRot,
THank you for the feedback, the file has been added.
