### ISSUE TITLE
Contained items sorting

### ISSUE THREAD

**Issue by matejsot** [ec-jrc/re3gistry#5]
On the list of contained items there is no possibility to sort the list by columns.

It should also be possible to hide non-valid items.

**Comment by emanuelaepure10** [comment]
Dear @matejsot 

In the latest version of the software there is the possibility to sort the table of the contained items my column
and the items shown are just the valid items.

Thank you

**Comment by unaibrrgn** [comment]
The solution given has been tested and works correctly @matejsot.

Thank you!
