### ISSUE TITLE
Error in the homepage in the UI (registers not listed)

### ISSUE THREAD

**Issue by AntoRot** [ec-jrc/re3gistry#50]
I updated the Italian registry (in the dev environment yet) to the latest version of the solution (even though I didn't set up the RSS release note automatic generation due to the missing example "release-note.xml" file - see [issue 48](https://github.com/ec-jrc/re3gistry/issues/48)) , but I continue to get an error in the homepage of the web interface published by installing the webapp.

In the homepage indeed the registers included in the registry are not listed, but the error shown in the image below appears:

![homepage-s](https://user-images.githubusercontent.com/7059416/119864645-1eff4480-bf1b-11eb-8000-cb16bed65a2d.png)

corresponding to the UI request http://10.14.251.252/registry2/rest?uri=http%3A%2F%2F93.147.186.152%2Fregistry2%2F&lang=it&format=jsonc.

If I make a search it works properly as shown in the image below:

![search-s](https://user-images.githubusercontent.com/7059416/119866905-9635d800-bf1d-11eb-9e71-014f6b86dab4.png)

where for each search result the item and the source register are returned.
While the URL linked to the item is proper and the related page returns (as you can see in the image below),

![result-item-s](https://user-images.githubusercontent.com/7059416/119868432-51ab3c00-bf1f-11eb-9f13-2393f83b3756.png)

that one linked to all source registers is http://10.14.251.252/registry2/undefined.

I noticed that a similar error is also got in the homepage of the sandbox registry https://inspire.geoase.eu/registry mentioned by @geoase in the [issue 41](https://github.com/ec-jrc/re3gistry/issues/41). See image below

![au-homepage](https://user-images.githubusercontent.com/7059416/119869038-15c4a680-bf20-11eb-8ad9-5faa02049412.png)

I couldn't understand if what described depends on not proper configurations or a bug.

Could you help me?

Thank you very much for your support!

**Comment by emanuelaepure10** [comment]
Hi @AntoRot 

Could you please check if in the file 
Re3gistry2ServiceWebappExternal/public_html/js/app_common.js

at the line 25-26 you have the following code
const key_json = 'json';
const key_jsonc = 'jsonc';

Thank you in advanced

**Comment by AntoRot** [comment]
Dear @emanuelaepure10,

Yes, those constants are declared in the file app_common.js.

The version currently installed is indeed the latest one, i.e. 2.2.0.

Thank you,
Antonio

**Comment by emanuelaepure10** [comment]
Dear @AntoRot 

Could you please check if you have any kind of error in the browser console?

Thank you

**Comment by AntoRot** [comment]
Hi @emanuelaepure10 

In the image below the error in the browser console.

![image001](https://user-images.githubusercontent.com/7059416/121017245-5c769400-c79d-11eb-98b7-4e453ca228a9.png)

Thank you,
Antonio

**Comment by emanuelaepure10** [comment]
Hi @AntoRot 

Here is the problem. Seems that the new code was not taken. Can you please redeplay the app? Stop and restart tomcat.
Seems that from your side is still calling 
the format .json (as it was before we solved the bug) 
instead of .jsonc (as it should be with the new code).

Thank you,
Emanuela

**Comment by AntoRot** [comment]
Sorry @emanuelaepure10,

That one shared was indeed a screenshot taken before the latest versions were installed. Don't take into account it.
Anyway, I continue to get a similar error (maybe with the final jsonc like the UI request reported at the beginning in the issue) also after installing the latest version.

I will share an updated screenshot asap as now I can't access the server.

Thank you,
Antonio

**Comment by AntoRot** [comment]
Hi @emanuelaepure10,

At the first access (or after clearing the cache) the error raised is the following

![error-element](https://user-images.githubusercontent.com/7059416/121491154-fde82a80-c9d5-11eb-8803-6a3625b6080f.png)

In the image you can also see the errors in the browser console.

At the next accesses, the error is the following:

![error-format](https://user-images.githubusercontent.com/7059416/121491368-2b34d880-c9d6-11eb-9f0a-fd5d04a0aeb0.png)

And this is the Tomcat log

```txt
10.14.251.252 - - [09/Jun/2021:17:30:09 +0200] "GET /re3gistry2restapi/items/any?uri=http%3A%2F%2F10.14.251.252%2Fregistry2%2F&lang=undefined&format=jsonc HTTP/1.1" 406 146
10.14.251.252 - - [09/Jun/2021:17:32:50 +0200] "GET /re3gistry2restapi/items/any?uri=http%3A%2F%2F10.14.251.252%2Fregistry2%2F&format=jsonc HTTP/1.1" 404 117
209.141.59.244 - - [09/Jun/2021:17:34:47 +0200] "GET /manager/html HTTP/1.1" 401 2473
162.62.123.46 - - [09/Jun/2021:17:34:51 +0200] "GET / HTTP/1.1" 200 11250
209.141.59.244 - - [09/Jun/2021:17:35:43 +0200] "GET /is_test HTTP/1.1" 404 1077
209.141.59.244 - - [09/Jun/2021:17:37:17 +0200] "GET /manager/html HTTP/1.1" 401 2473
209.141.59.244 - - [09/Jun/2021:17:37:17 +0200] "GET /manager/html HTTP/1.1" 401 2473
209.141.59.244 - - [09/Jun/2021:17:37:17 +0200] "GET /manager/html HTTP/1.1" 401 2473
209.141.59.244 - - [09/Jun/2021:17:37:17 +0200] "GET /manager/html HTTP/1.1" 401 2473
209.141.59.244 - - [09/Jun/2021:17:37:18 +0200] "GET /manager/html HTTP/1.1" 401 2473
209.141.59.244 - - [09/Jun/2021:17:37:18 +0200] "GET /manager/html HTTP/1.1" 401 2473
209.141.59.244 - - [09/Jun/2021:17:37:18 +0200] "GET /manager/html HTTP/1.1" 401 2473
209.141.59.244 - - [09/Jun/2021:17:37:19 +0200] "GET /manager/html HTTP/1.1" 401 2473
209.141.59.244 - - [09/Jun/2021:17:37:19 +0200] "GET /manager/html HTTP/1.1" 401 2473
209.141.59.244 - - [09/Jun/2021:17:37:19 +0200] "GET /manager/html HTTP/1.1" 401 2473
209.141.59.244 - - [09/Jun/2021:17:37:20 +0200] "GET /manager/html HTTP/1.1" 401 2473
209.141.59.244 - - [09/Jun/2021:17:37:20 +0200] "GET /manager/html HTTP/1.1" 401 2473
209.141.59.244 - - [09/Jun/2021:17:37:20 +0200] "GET /manager/html HTTP/1.1" 401 2473
209.141.59.244 - - [09/Jun/2021:17:37:21 +0200] "GET /manager/html HTTP/1.1" 401 2473
209.141.59.244 - - [09/Jun/2021:17:37:21 +0200] "GET /manager/html HTTP/1.1" 401 2473
209.141.59.244 - - [09/Jun/2021:17:37:21 +0200] "GET /manager/html HTTP/1.1" 401 2473
10.14.251.252 - - [09/Jun/2021:17:41:47 +0200] "GET /re3gistry2restapi/items/any?uri=http%3A%2F%2F10.14.251.252%2Fregistry2%2F&lang=undefined&format=jsonc HTTP/1.1" 406 146
10.14.251.252 - - [09/Jun/2021:17:42:56 +0200] "GET /re3gistry2restapi/items/any?uri=http%3A%2F%2F10.14.251.252%2Fregistry2%2F&lang=undefined&format=jsonc HTTP/1.1" 406 146
10.14.251.252 - - [09/Jun/2021:17:46:11 +0200] "GET /re3gistry2restapi/items/any?uri=http%3A%2F%2F93.147.186.152%2Fregistry2%2F&format=jsonc HTTP/1.1" 404 117
10.14.251.252 - - [09/Jun/2021:17:46:56 +0200] "GET /re3gistry2restapi/items/any?uri=http%3A%2F%2F93.147.186.152%2Fregistry2%2F&lang=undefined&format=jsonc HTTP/1.1" 406 146
10.14.251.252 - - [09/Jun/2021:17:47:16 +0200] "GET /re3gistry2restapi/items/any?uri=http%3A%2F%2F93.147.186.152%2Fregistry2%2F&lang=undefined&format=jsonc HTTP/1.1" 406 146
10.14.251.252 - - [09/Jun/2021:17:47:25 +0200] "GET /re3gistry2restapi/items/any?uri=http%3A%2F%2F93.147.186.152%2Fregistry2%2F&lang=undefined&format=jsonc HTTP/1.1" 406 146
10.14.251.252 - - [09/Jun/2021:17:47:51 +0200] "GET /re3gistry2restapi/items/any?uri=http%3A%2F%2F93.147.186.152%2Fregistry2%2F&lang=undefined&format=jsonc HTTP/1.1" 406 146
10.14.251.252 - - [09/Jun/2021:17:50:42 +0200] "GET /re3gistry2restapi/items/any?uri=http%3A%2F%2F93.147.186.152%2Fregistry2%2F&format=jsonc HTTP/1.1" 404 117
```

Thank you,
Antonio

**Comment by emanuelaepure10** [comment]
Hi @AntoRot 

Can you please check in the index.html page which of the languages you have added to your system has as default setted the active/selected language, so the class called "ecl-language-list__item--is-active"?

Thank you in advanced
Emanuela

**Comment by AntoRot** [comment]
Hi @emanuelaepure10,
in the index.html page the active language is "en", i.e.:

```html
<li class="ecl-language-list__item list-group-item ecl-language-list__item--is-active"><a lang="en" hrefLang="en"
                                                                                                                              rel="alternate" href="#language_en"
class="ecl-language-list__link ecl-link ecl-link--standalone ecl-link--icon ecl-link--icon-after"><span class="ecl-link__label">English</span> <i class="fas fa-check"></i></a></li>
<li class="ecl-language-list__item list-group-item"><a lang="it" hrefLang="it" rel="alternate"
                                                                                           href="#language_it"
                                                                                           class="ecl-language-list__link ecl-link ecl-link--standalone">italiano</a></li>
```

I changed it, i.e.:

```html
<li class="ecl-language-list__item list-group-item ecl-language-list__item--is-active"><a lang="it" hrefLang="it"
                                                                                                                              rel="alternate" href="#language_it"
class="ecl-language-list__link ecl-link ecl-link--standalone ecl-link--icon ecl-link--icon-after"><span class="ecl-link__label">italiano</span> <i class="fas fa-check"></i></a></li>
<li class="ecl-language-list__item list-group-item"><a lang="en" hrefLang="en" rel="alternate"
                                                                                           href="#language_en"
                                                                                           class="ecl-language-list__link ecl-link ecl-link--standalone">English</a></li>
```

but it continues not to work.

In the conf/conf.js I had set registryApp.defaultLanguage = 'it'.

Thank you,
Antonio

**Comment by emanuelaepure10** [comment]
Hi @AntoRot 

Could you please check in the database the table reg_languagecode and see which of the en or it is setted as masterlanguage true?
Than, could you from the interface button "cambia lingua" see which is the language selected? please select the other one and see if in this way the page is loaded correctly.

Thank you

**Comment by emanuelaepure10** [comment]
Ciao @AntoRot 

Please checkout the latest release 
https://github.com/ec-jrc/re3gistry/releases/tag/v2.2.1

This should solve the problem.

Thank you

**Comment by AntoRot** [comment]
Dear @emanuelaepure10,

Maybe you wanted to refer to v. 2.2.2.

I'll update our registry to that release and let you know.

Thank you very much,
Antonio

**Comment by emanuelaepure10** [comment]
Yes @AntoRot 

Sorry, I have paste the wrong link.
I was indead refering to the https://github.com/ec-jrc/re3gistry/releases/tag/v2.2.2

Keep us updated
Best regards,
Emanuela

**Comment by AntoRot** [comment]
Hi @emanuelaepure10,

I don't get the error "The format or language specified in the request is not available. Please specify a supported format/language ..." anymore, but I continue to get the error you can see in the image below.

![error-hp-222](https://user-images.githubusercontent.com/7059416/122401629-1085d500-cf7d-11eb-9a31-806b2f855dda.jpg)

Thank you,
Antonio

**Comment by emanuelaepure10** [comment]
Thank you for your feedback.
The issue has been fixed in the release https://github.com/ec-jrc/re3gistry/releases/tag/v2.2.3

Best regards
