### ISSUE TITLE
Tomcat error prevents re3gistry2 app from starting

### ISSUE THREAD

**Issue by fabiovinci** [ec-jrc/re3gistry#52]
I installed version 2.2.0 of the Re3gistry2 on a Ubuntu server (20.04.2 LTS), with the following versions of the needed software:

- OpenJDK 1.8.0_292 
- Apache Tomcat 8.5.66 
- Solr 8.8.2 
- PostgreSQL 9.6

I followed all the steps provided in the "Administrator manual" but I receive an error in Tomcat that prevents the starting of the app.

The error details are visible in the screenshot:

![Error](https://user-images.githubusercontent.com/22212406/121219341-e13bdd80-c883-11eb-9b27-4ff8ed4fe139.png)

Could you please provide your feedback?

Thank you for your support!

**Comment by df-git** [comment]
Thank you for the feedback.
A [new release](https://github.com/ec-jrc/re3gistry/releases/tag/v2.2.1) has just been published.
