### ISSUE TITLE
Fields wrongly visible in the overview table

### ISSUE THREAD

**Issue by AntoRot** [ec-jrc/re3gistry#53]
For some fields I didn't tick the option to show them in table, as you can see in the image below

![structure](https://user-images.githubusercontent.com/7059416/123414961-d6d45000-d5b4-11eb-908e-c8be80ae8a58.png)

but those fields continue to be visible in the overview table in the web interface, as you can see in the image below

![ui-showtable](https://user-images.githubusercontent.com/7059416/123415027-f23f5b00-d5b4-11eb-878a-d63720a7bbe9.png)

**Comment by emanuelaepure10** [comment]
Thank you for your feedback.
The issue has been fixed in the release https://github.com/ec-jrc/re3gistry/releases/tag/v2.2.3

Best regards
