### ISSUE TITLE
Wrong path for some items in the search results

### ISSUE THREAD

**Issue by AntoRot** [ec-jrc/re3gistry#54]
I performed a search in the Italian registry web interface and I noticed that in case of a hierarchical register the path for some items in the search results page is not properly created.

In the image below an example of that case:

![wrong-path](https://user-images.githubusercontent.com/7059416/123429428-3d626980-d5c7-11eb-92e6-6032d9d16d3e.png)
 
The right path for the item would be /ict-professional-profiles/systemsAnalyst/geoDataAnalyst but that one created in the results page is /ict-professional-profiles/geoDataAnalyst.

**Comment by df-git** [comment]
Dear @AntoRot,
This problem is related to an old/broken Solr index. If you start a re-index, the problem will be solved.
