### ISSUE TITLE
If a codelist is "retired", its codelist values should be retired accordingly.

### ISSUE THREAD

**Issue by fabiovinci** [ec-jrc/re3gistry#55]
I created a codelist and I defined some codelist values, then I "retired" it but all the codelist values still show the status "Valid".

I used version 2.2 on Ubuntu 20.4 server.

The expected behaviour should be that if the user "retires" a codelist all the related codelist values should be automatically retired.

Is that correct?

![image](https://user-images.githubusercontent.com/22212406/124290394-ac096f00-db53-11eb-9107-5b794afca974.png)

**Comment by AntoRot** [comment]
Similar to that, I encountered this situation: an item is set in the status "retired" in the management tool, i.e.

![status-retired-mngt](https://user-images.githubusercontent.com/7059416/125975979-ed123eb9-97cb-4d55-85d7-e1dc7866c7a6.png)

 but the status shown for that item in the registry web interface is "valid", i.e.

![status-retired-UI](https://user-images.githubusercontent.com/7059416/125976026-c0932010-f069-443a-801d-8315f20bd7d9.png)

**Comment by emanuelaepure10** [comment]
@AntoRot We have solved this issue with the latest update.

We have added in our feature plans the issue that @fabiovinci encountered to retire all the children once the parent is retired.

Thank you both
Emanuela

**Comment by emanuelaepure10** [comment]
Corrected with the commit
https://github.com/ec-jrc/re3gistry/commit/29dc22490d75e33d1bb44a65995e4f149af5dcbf
