### ISSUE TITLE
Status not found in webapp

### ISSUE THREAD

**Issue by geoase** [ec-jrc/re3gistry#58]
Hi,
for my Registry setup the status requests to the rest backend are returning 404.

https://inspire.geoase.eu/status/valid

Do you have any ideas how I can solve this?

Thank you already
G

**Comment by emanuelaepure10** [comment]
Hi,

Could you please check in your reg_statusgroup table the baseuri for the status?

If you plan to keep the same items for the status that we have in INSPIRE we would recomand you to keep the baseuri for the status http://inspire.ec.europa.eu/registry and in this way you point to the common place.

Thank you

**Comment by geoase** [comment]
Hi Emanuela,
works like a charm. Thank you.
G
