### ISSUE TITLE
Parent codelists

### ISSUE THREAD

**Issue by geoase** [ec-jrc/re3gistry#59]
# Background and Motivation
If I understand correctly for registry 1.3 codelist children are listed as items within a parent codelist:

https://inspire.ec.europa.eu/codelist/ClassificationItemTypeValue
https://inspire.ec.europa.eu/codelist/AgeBy5YearsValue

# Proposed change
Is it feasible/possible to provide an option in order to list children of items as elements in the table of the parent item?

# Alternatives
Or is there another option to create "containers" of codelists? e.g in Austria it would be necessary to create different LandUse codelists for federal states and it would be great to collect them in a container of some sort.

Thanks
G

**Comment by emanuelaepure10** [comment]
Hi @geoase ,

We are doing exactly the same as we were doing in the version 1.3 as well in the new version 2.0.
You can add items with a parent, than in the parent view you will see the list of children items.

Can you please try to do it and let us know if everything is as expected?

Best regards,

**Comment by geoase** [comment]
This is fine, thank you. Can be closed.
