### ISSUE TITLE
Not active hyperlinks in the Contained items list

### ISSUE THREAD

**Issue by matejsot** [ec-jrc/re3gistry#6]
In the Contained items list there is a field with hyperlink (webpage):
![contained items link](https://user-images.githubusercontent.com/60505136/74413048-f1ce7600-4e3e-11ea-8b08-963f1ca8c3a4.JPG)
I inserted the link for the item SI.GURS, but it is not active on the list.

**Comment by df-git** [comment]
Dear @matejsot,
The link in the table was not foreseen for external links. As you can see in the tables, there are link only to internal items. The links are then rendered in the service front-end (second screenshot).

Furthermore, 2 of the elements in the table are compiled in the wrong way: to have the hyperlink you need to put the URL in the "link" field (as correctly done in the "SI.GURS" item).

![image](https://user-images.githubusercontent.com/29379252/74655426-9e389100-518c-11ea-8603-076f89240c2f.png)

![image](https://user-images.githubusercontent.com/29379252/74655905-772e8f00-518d-11ea-88d0-c0fcbf67801d.png)
