### ISSUE TITLE
The relationalReference field - hiding not valid values

### ISSUE THREAD

**Issue by matejsot** [ec-jrc/re3gistry#7]
When adding an item that has a relationalReference field, it should display only valid values. Now you can choose also an invalid, retired or superseded value. On the screenshot: 3 values are valid, other 3 are not - since they have the same label it is impossible to tell which is which.
![contained items relationalReference](https://user-images.githubusercontent.com/60505136/74413617-0b23f200-4e40-11ea-8525-eb45c5e7aae9.JPG)

**Comment by df-git** [comment]
Dear @matejsot,
We solved the issue and published the solution on the test-bed.
The drop-down shows now only valid values.
Thank you for your feedback.

**Comment by matejsot** [comment]
I confirm the solution.
