### ISSUE TITLE
Question regarding eclipselink.ddl-generation = create-tables

### ISSUE THREAD

**Issue by heidivanparys** [ec-jrc/re3gistry#72]
I was wondering whether `eclipselink.ddl-generation` actually should be set to `create-tables`, 

https://github.com/ec-jrc/re3gistry/blob/79f806053066cfa1fb1636ce34b64912004ccb32/dist/app/re3gistry2/WEB-INF/classes/META-INF/persistence.xml.orig#L41

https://github.com/ec-jrc/re3gistry/blob/173c5b08d9af5ee7eb32a4152056a829ba7285be/sources/Re3gistry2-build-helper/pom.xml#L17

given the fact that the database initialization script has been run already, https://github.com/ec-jrc/re3gistry/blob/master/documentation/administrator-manual.md#database-setup? Or I am missing something here?

**Comment by emanuelaepure10** [comment]
Dear @heidivanparys 

Thank you for asking it.

I think that the best value should be "none" (default value of EclipseLink), 
as we dont create the tables using EclipseLink.

We should test it. 
If you can and have time to test it would be a great help.

Thank you 
Emanuela

**Comment by heidivanparys** [comment]
It worked fine for me, setting the value to none.
