### ISSUE TITLE
Possible bug: regItemProposedToRegItem method

### ISSUE THREAD

**Issue by dhbello** [ec-jrc/re3gistry#75]
I believe that there is a bug when a relation field is tried to be updated (a single value field gets two values). To reproduce it, follow these steps:

- Update any item relation field (RegItemproposedHandler.updateFields creates with two RegLocalizationProposed records - two different fieldValueIndex)
- Follow all the acceptance process (submit the action, approve it, etc)
- When the admin is going to publish the action (RegItemHandler.regItemProposedToRegItem method), the previous value (ej: fieldValueIndex 0) is not deleted, and the new value (ej: fieldValueIndex 1) is saved. Therefore, a single value field receives two values.

My solution was before create/save RegLocalization values, previously delete and renumerate fieldValueIndex values, however, I'm not sure if this is a bug, so I didn't submit a merge/patch.

**Comment by oruscalleda** [comment]
This bug is no longer reproducible, so this issue will be closed
