### ISSUE TITLE
define a parent

### ISSUE THREAD

**Issue by krisdc** [ec-jrc/re3gistry#8]
for Specific Hazard Type I addd two concepts, first precipitation than heavy snowfall as narrower concept. to define a parent was possible (running out of time

To help us investigate the issue, you may want to include:

- [ x] a description of the steps to reproduce your issue
- [ X] the browser and version used
- [ ] a screenshot illustrating the problem
- [ ] the Test Report (ideally as an attachment to the issue)
- [ ] the name of the Test that failed or better: change the `Level of Detail`
in the Report by clicking on `All Details`, then scroll down to the failed test
and copy the Link on the right-hand side of the `Assertion URI`
- [ ] the URL of your service / the file you have uploaded or referenced (as
an attachment).

If your service is protected or you have confidential data that you cannot
upload here, you can request an email address to which you can send URLs / files.
Please note that issues cannot be investigated for services/datasets that we cannot
access.

**Comment by df-git** [comment]
Dear Chris,
The high time required to load the list of selectable parents is due to the high numbers of items to be loaded. A possible improvement is to cache the elements at startup or to just provide a search interface from which write the element ame/id ad ten select from a list of results.

**Comment by jescriu** [comment]
Dear @krisdc,

We are analysing, togetehr with our contractors, the issues opened in the Re3gistry repository and the feasibility to tackle them in the short term taking into account the resources available.

We found this issue which was opened quite a long time ago and unfortunately was not apprppiately followed-up.

Question:

1. Is it still an issue for you?
2. If so, could you please clarfy its description? - We had issues to understand the first sentence:

> 
for Specific Hazard Type I addd two concepts, first precipitation than heavy snowfall as narrower concept. to define a parent was possible (running out of time

Thank you!

**Comment by jescriu** [comment]
Dear @krisdc,
After a reasonable period, we proceed to close this issue.
Feel free to open it again in case it is still an issue for you.
