### ISSUE TITLE
Showing the status values in the public front-end gives a JS error

### ISSUE THREAD

**Issue by heidivanparys** [ec-jrc/re3gistry#84]
When accessing the URI for the list of statuses, or a particular status, the page keeps on showing the spinner, and when investigating more closely, an error is thrown in script app_core.js

It seems that the application is assuming that a normal item is loaded, and normal items are versioned, but this does not apply for statuses, resulting in the error below.

![image](https://user-images.githubusercontent.com/11427611/142889674-f5477198-6fe6-4757-848b-bb3bb6cfa201.png)

Normal items load fine.

![image](https://user-images.githubusercontent.com/11427611/142890518-2128297d-4779-4175-ba3a-dec7b09d5f8f.png)

**Comment by emanuelaepure10** [comment]
Solved by the latest commits.
