### ISSUE TITLE
csv template

### ISSUE THREAD

**Issue by krisdc** [ec-jrc/re3gistry#9]
_Please follow the template below and provide at least information for
the first 4 sections_

# Background and Motivation
I'm strong interested on bulk imports, because to test the potential feasibility on MS level. 
My attributes in the csv are not accepted.

# Proposed change
could you provide an example of a correct csv file in the documentation

# Alternatives
a smart option would be, if I go directly to a content - code list like Specific Hazard Type, create a "dynamic" template which contains items like natural risk zones for the theme.

# Funding
Is there full or partial funding available for implementing this proposal?

# Additional information
This is an optional section for additional information. These could include,
for example:
- the impact of this improvement proposal, known risks or compatibility issues
on existing deployments.
- (time) constraints, if this proposal is fully or partially funded

**Comment by df-git** [comment]
Dear Chris,
Thank you for your message. The Re3istey 2 available on the sandbox, already integrates the bulk import system, that is providing also an example template. 
This feature will be documented in the user guide available with the official release of the software.

![bukk-import](https://user-images.githubusercontent.com/29379252/78564273-7b396d80-781c-11ea-8899-a1bf089045a7.png)
