### ISSUE TITLE
Property application.status.baseuri should be removed from the configuration files

### ISSUE THREAD

**Issue by heidivanparys** [ec-jrc/re3gistry#98]
Property `application.status.baseuri` should be removed from the configuration files (configuration.properties) and the code in `eu.europa.ec.re3gistry2.javaapi.solr.SolrHandler.indexItem(RegItem, EntityManager)` be updated to retrieve the status base URI from the database instead.

See also discussion starting at https://github.com/ec-jrc/re3gistry/pull/96#issuecomment-977925400

**Comment by emanuelaepure10** [comment]
Please check the last commit, it should remove at all the application.status.baseuri
